=== eclipse-sumo/sumo/data/xsd/edges_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:include schemaLocation="types/base.xsd"/>

    <xsd:element name="edges" type="edgesType">
        <xsd:key name="edgeKey">
            <xsd:selector xpath="edge"/>
            <xsd:field xpath="@id"/>
        </xsd:key>
    </xsd:element>

    <xsd:complexType name="edgesType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="location" type="locationType" maxOccurs="1"/>
            <xsd:element name="edge" type="edgeType"/>
            <xsd:element name="roundabout" type="roundaboutType"/>
            <xsd:element name="delete" type="deleteType"/>
        </xsd:choice>
        <xsd:attribute name="version" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="\d+.\d+"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="edgeType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="lane" type="laneType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="split" type="splitType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="neigh" type="neighType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="stopOffset" type="stopOffsetType" minOccurs="0" maxOccurs="1"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="from" type="xsd:string" use="required"/>
        <xsd:attribute name="to" type="xsd:string" use="required"/>
        <xsd:attribute name="name" type="xsd:string" use="optional"/>
        <xsd:attribute name="priority" type="xsd:int" use="optional"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="routingType" type="xsd:string" use="optional"/>
        <xsd:attribute name="numLanes" type="xsd:positiveInteger" use="optional"/>
        <xsd:attribute name="speed" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="friction" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="shape" type="shapeType" use="optional"/>
        <xsd:attribute name="spreadType" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="center"/>
                    <xsd:enumeration value="roadCenter"/>
                    <xsd:enumeration value="right"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="length" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="width" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="endOffset" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="allow" type="xsd:string" use="optional"/>
        <xsd:attribute name="disallow" type="xsd:string" use="optional"/>
        <xsd:attribute name="distance" type="floatType"/>
        <xsd:attribute name="bidi" type="xsd:string" use="optional"/>
        <xsd:attribute name="sidewalkWidth" type="nonNegativeFloatType"/>
        <xsd:attribute name="bikeLaneWidth" type="nonNegativeFloatType"/>
    </xsd:complexType>

    <xsd:complexType name="laneType">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="neigh" type="neighType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="stopOffset" type="stopOffsetType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="index" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="allow" type="xsd:string" use="optional"/>
        <xsd:attribute name="disallow" type="xsd:string" use="optional"/>
        <xsd:attribute name="speed" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="friction" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="width" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="prefer" type="xsd:string" use="optional"/>
        <xsd:attribute name="acceleration" type="boolType" use="optional"/>
        <xsd:attribute name="endOffset" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="shape" type="shapeType" use="optional"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="changeRight" type="xsd:string" use="optional"/>
        <xsd:attribute name="changeLeft" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="deleteType">
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="index" type="xsd:nonNegativeInteger" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="roundaboutType">
        <xsd:attribute name="nodes" type="xsd:string" use="optional"/>
        <xsd:attribute name="edges" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="neighType">
        <xsd:attribute name="lane" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="stopOffsetType">
        <xsd:attribute name="value" type="nonNegativeFloatType" use="required"/>
        <xsd:attribute name="exceptions" type="xsd:string" use="optional"/>
        <xsd:attribute name="vClasses" type="xsd:string" use="optional"/>
    </xsd:complexType>

</xsd:schema>

=== eclipse-sumo/sumo/tests/netedit/processing/join_selected_junction/near_position/net.edg.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2024-08-08 14:13:57 by Eclipse SUMO netedit Version v1_20_0+1772-b761cf9d6e3
<neteditConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/neteditConfiguration.xsd">

    <input>
        <sumo-net-file value="D:\Netedit_dev\tests\netedit\processing\join_selected_junction\near_position\net.net.xml"/>
    </input>

    <processing>
        <geometry.min-radius.fix.railways value="false"/>
        <geometry.max-grade.fix value="false"/>
        <offset.disable-normalization value="true"/>
        <lefthand value="0"/>
    </processing>

    <junctions>
        <no-turnarounds value="true"/>
        <junctions.corner-detail value="5"/>
        <junctions.limit-turn-speed value="5.50"/>
        <rectangular-lane-cut value="0"/>
    </junctions>

    <pedestrian>
        <walkingareas value="0"/>
    </pedestrian>

</neteditConfiguration>
-->

<edges version="1.20" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/edges_file.xsd">
    <location netOffset="0.00,0.00" convBoundary="-60.00,-30.00,60.00,30.00" origBoundary="-10000000000.000000,-10000000000.000000,10000000000.000000,10000000000.000000" projParameter="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"/>

    <edge id="-E0" from="J1" to="J0" priority="-1" numLanes="1" speed="13.89" disallow="pedestrian"/>
    <edge id="-E1" from="J2" to="J1" priority="-1" numLanes="1" speed="13.89" disallow="pedestrian"/>
    <edge id="-E2" from="J3" to="J0" priority="-1" numLanes="1" speed="13.89" disallow="pedestrian"/>
    <edge id="-E3" from="J4" to="J0" priority="-1" numLanes="1" speed="13.89" disallow="pedestrian"/>
    <edge id="-E4" from="J6" to="J1" priority="-1" numLanes="1" speed="13.89" disallow="pedestrian"/>
    <edge id="-E5" from="J7" to="J1" priority="-1" numLanes="1" speed="13.89" disallow="pedestrian"/>
    <edge id="-E7" from="J9" to="J0" priority="-1" numLanes="1" speed="13.89" disallow="pedestrian"/>
    <edge id="E0" from="J0" to="J1" priority="-1" numLanes="1" speed="13.89" disallow="pedestrian"/>
    <edge id="E1" from="J1" to="J2" priority="-1" numLanes="1" speed="13.89" disallow="pedestrian"/>
    <edge id="E2" from="J0" to="J3" priority="-1" numLanes="1" speed="13.89" disallow="pedestrian"/>
    <edge id="E3" from="J0" to="J4" priority="-1" numLanes="1" speed="13.89" disallow="pedestrian"/>
    <edge id="E4" from="J1" to="J6" priority="-1" numLanes="1" speed="13.89" disallow="pedestrian"/>
    <edge id="E5" from="J1" to="J7" priority="-1" numLanes="1" speed="13.89" disallow="pedestrian"/>
    <edge id="E7" from="J0" to="J9" priority="-1" numLanes="1" speed="13.89" disallow="pedestrian"/>
    <edge id="EdgeExternBot" from="JunctionExtern0" to="JunctionExtern1" priority="-1" numLanes="1" speed="13.89" shape="-60.00,0.00 -45.00,0.00 -45.00,-25.00 -40.00,-30.00 40.00,-30.00 45.00,-25.00 45.00,0.00 60.00,0.00" length="175.00" width="3.00" disallow="pedestrian"/>
    <edge id="EdgeExternTop" from="JunctionExtern1" to="JunctionExtern0" priority="-1" numLanes="1" speed="13.89" shape="60.00,0.00 45.00,0.00 45.00,25.00 40.00,30.00 -40.00,30.00 -45.00,25.00 -45.00,0.00 -60.00,0.00" length="175.00" width="3.00" disallow="pedestrian"/>
</edges>

=== eclipse-sumo/sumo/tests/netconvert/function/crossings/guessed/tl_controlled_path/input_plain.edg.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on Mon 17 Mar 2014 03:48:51 PM CET by Netedit Version dev-SVN-r15873
This data file and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
SPDX-License-Identifier: EPL-2.0
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://sumo.dlr.de/xsd/netedit.exeConfiguration.xsd">

    <input>
        <sumo-net-file value="net3b.net.xml"/>
    </input>

    <output>
        <output-file value="net3b.net.xml"/>
        <plain-output-prefix value="/scr1/erdm_ja/sip-svn-trunk/projects/colombo/prototype3/input_plain"/>
    </output>

    <processing>
        <no-turnarounds value="true"/>
        <offset.disable-normalization value="true"/>
    </processing>

</configuration>
-->

<edges version="0.13" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://sumo.dlr.de/xsd/edges_file.xsd">
    <edge id="AB" from="A" to="B" priority="1" numLanes="1" speed="13.89">
        <lane index="0" allow="pedestrian"/>
    </edge>
    <edge id="BC" from="B" to="C" priority="1" numLanes="1" speed="13.89">
        <lane index="0" allow="pedestrian"/>
    </edge>
    <edge id="CD" from="C" to="D" priority="1" numLanes="1" speed="13.89">
        <lane index="0" allow="pedestrian"/>
    </edge>
    <edge id="DE" from="D" to="E" priority="1" numLanes="1" speed="13.89">
        <lane index="0" allow="pedestrian"/>
    </edge>
</edges>

=== eclipse-sumo/sumo/tests/netconvert/bugs/ticket13542b/input_plain.edg.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2023-07-05 16:41:19 by Eclipse SUMO netedit Version v1_18_0+0121-c04b76e
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/neteditConfiguration.xsd">

    <input>
        <sumo-net-file value="net2.net.xml"/>
    </input>

    <output>
        <output.street-names value="true"/>
    </output>

    <processing>
        <geometry.min-radius.fix.railways value="false"/>
        <geometry.max-grade.fix value="false"/>
        <offset.disable-normalization value="true"/>
        <lefthand value="0"/>
    </processing>

    <junctions>
        <no-internal-links value="false"/>
        <no-turnarounds value="true"/>
        <junctions.corner-detail value="5"/>
        <junctions.limit-turn-speed value="5.50"/>
        <rectangular-lane-cut value="0"/>
    </junctions>

    <pedestrian>
        <walkingareas value="1"/>
    </pedestrian>

</configuration>
-->

<edges version="1.16" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/edges_file.xsd">
    <location netOffset="-398816.96,-5809707.61" convBoundary="2072.35,575.16,2177.85,706.33" origBoundary="13.510966,52.428677,13.569823,52.453865" projParameter="+proj=utm +zone=33 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"/>

    <edge id="-23925119#3" from="cluster_261705708_8243171049_987195315_9945733967" to="cluster_259404814_9945733960_9945733961" name="Weerthstraße" priority="3" type="highway.residential" numLanes="1" speed="8.33" shape="2126.74,641.06 2148.26,654.34" disallow="pedestrian tram rail_urban rail rail_electric rail_fast ship">
        <lane index="0">
            <param key="origId" value="23925119"/>
        </lane>
        <param key="origFrom" value="8243171049"/>
        <param key="origTo" value="259404814"/>
    </edge>
    <edge id="1085421712#0" from="9945733963" to="10669437595" priority="1" type="highway.footway" numLanes="1" speed="2.78" spreadType="center" width="2.00" allow="pedestrian">
        <lane index="0">
            <param key="origId" value="1085421712"/>
        </lane>
    </edge>
    <edge id="1085421712#1" from="10669437595" to="9945733962" priority="1" type="highway.footway" numLanes="1" speed="2.78" spreadType="center" width="2.00" allow="pedestrian">
        <lane index="0">
            <param key="origId" value="1085421712"/>
        </lane>
    </edge>
    <edge id="1085421712#2" from="9945733962" to="cluster_261705708_8243171049_987195315_9945733967" priority="1" type="highway.footway" numLanes="1" speed="2.78" shape="2120.03,650.31 2112.52,646.06" spreadType="center" width="2.00" allow="pedestrian">
        <lane index="0">
            <param key="origId" value="1085421712"/>
        </lane>
        <param key="origTo" value="987195315"/>
    </edge>
    <edge id="1085421714#0" from="cluster_261705708_8243171049_987195315_9945733967" to="9945733959" priority="1" type="highway.footway" numLanes="1" speed="2.78" shape="2130.34,636.46 2157.26,652.78" spreadType="center" width="2.00" allow="pedestrian">
        <lane index="0">
            <param key="origId" value="1085421714"/>
        </lane>
        <param key="origFrom" value="9945733967"/>
    </edge>
    <edge id="1102336903#0" from="cluster_150751448_8243171047" to="cluster_261705708_8243171049_987195315_9945733967" name="Adlergestell" priority="12" type="highway.primary" numLanes="3" speed="13.89" shape="2169.86,575.16 2144.82,604.19 2119.81,636.71" spreadType="center" disallow="pedestrian bicycle tram rail_urban rail rail_electric rail_fast ship">
        <lane index="0">
            <param key="origId" value="1102336903"/>
        </lane>
        <lane index="1">
            <param key="origId" value="1102336903"/>
        </lane>
        <lane index="2">
            <param key="origId" value="1102336903"/>
        </lane>
        <param key="origFrom" value="150751448"/>
        <param key="origTo" value="261705708"/>
        <param key="ref" value="B 96a"/>
    </edge>
    <edge id="23925119#3" from="cluster_259404814_9945733960_9945733961" to="cluster_261705708_8243171049_987195315_9945733967" name="Weerthstraße" priority="3" type="highway.residential" numLanes="1" speed="8.33" shape="2148.26,654.34 2126.74,641.06" disallow="pedestrian tram rail_urban rail rail_electric rail_fast ship">
        <lane index="0">
            <param key="origId" value="23925119"/>
        </lane>
        <param key="origFrom" value="259404814"/>
        <param key="origTo" value="8243171049"/>
    </edge>
    <edge id="40191606" from="cluster_261705708_8243171049_987195315_9945733967" to="3246050936" name="Adlergestell" priority="12" type="highway.primary" numLanes="3" speed="13.89" shape="2112.52,646.06 2108.18,652.42 2089.68,679.56 2077.56,697.35 2076.64,698.71 2072.35,704.88" spreadType="center" disallow="pedestrian bicycle tram rail_urban rail rail_electric rail_fast ship">
        <lane index="0">
            <param key="origId" value="40191606"/>
        </lane>
        <lane index="1">
            <param key="origId" value="40191606"/>
        </lane>
        <lane index="2">
            <param key="origId" value="40191606"/>
        </lane>
        <param key="origFrom" value="987195315"/>
        <param key="ref" value="B 96a"/>
    </edge>
    <edge id="603467167#1" from="5728699319" to="10669437595" priority="1" type="highway.footway" numLanes="1" speed="2.78" spreadType="center" width="2.00" allow="pedestrian">
        <lane index="0">
            <param key="origId" value="603467167"/>
        </lane>
    </edge>
    <edge id="603467167#2" from="10669437595" to="10669437596" priority="1" type="highway.footway" numLanes="1" speed="2.78" shape="2121.60,651.02 2124.03,647.59 2126.87,646.00 2139.82,654.02 2140.64,660.18 2139.86,661.08" spreadType="center" width="2.00" allow="pedestrian">
        <lane index="0">
            <param key="origId" value="603467167"/>
        </lane>
    </edge>
    <edge id="85088361#1" from="246771374" to="cluster_261705708_8243171049_987195315_9945733967" priority="1" type="highway.footway" numLanes="1" speed="2.78" shape="2101.89,639.00 2112.52,646.06" spreadType="center" width="2.00" allow="pedestrian">
        <lane index="0">
            <param key="origId" value="85088361"/>
        </lane>
        <param key="origTo" value="987195315"/>
    </edge>
    <edge id="886496552#4" from="cluster_150751448_8243171047" to="cluster_261705708_8243171049_987195315_9945733967" priority="1" type="highway.path" numLanes="2" speed="5.56" shape="2177.85,580.20 2147.15,615.75 2130.73,636.77" spreadType="center">
        <lane index="0" allow="pedestrian" width="2.00">
            <param key="origId" value="886496552"/>
        </lane>
        <lane index="1" allow="bicycle" width="1.00">
            <param key="origId" value="886496552"/>
        </lane>
        <param key="origFrom" value="8243171047"/>
        <param key="origTo" value="9945733967"/>
    </edge>
    <edge id="886496552#6" from="cluster_261705708_8243171049_987195315_9945733967" to="9945733962" priority="1" type="highway.path" numLanes="2" speed="5.56" shape="2127.14,641.36 2120.43,650.60" spreadType="center">
        <lane index="0" allow="pedestrian" width="2.00">
            <param key="origId" value="886496552"/>
        </lane>
        <lane index="1" allow="bicycle" width="1.00">
            <param key="origId" value="886496552"/>
        </lane>
        <param key="origFrom" value="8243171049"/>
    </edge>
    <edge id="886496552#7" from="9945733962" to="10669437594" priority="1" type="highway.path" numLanes="2" speed="5.56" shape="2120.43,650.61 2115.42,657.41 2096.87,684.48 2084.28,701.97 2081.69,705.73" spreadType="center">
        <lane index="0" allow="pedestrian" width="2.00">
            <param key="origId" value="886496552"/>
        </lane>
        <lane index="1" allow="bicycle" width="1.00">
            <param key="origId" value="886496552"/>
        </lane>
    </edge>
</edges>

=== eclipse-sumo/sumo/tests/netedit/network/lanes/select_vtypes/allowed/rail/net.edg.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2024-07-01 08:42:09 by Eclipse SUMO netedit Version v1_20_0+1067-ecd6dc8927e
<neteditConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/neteditConfiguration.xsd">

    <input>
        <sumo-net-file value="D:\Netedit_dev\tests\netedit\network\lanes\select_vtypes\allowed\aircraft\net.net.xml"/>
    </input>

    <processing>
        <geometry.min-radius.fix.railways value="false"/>
        <geometry.max-grade.fix value="false"/>
        <offset.disable-normalization value="true"/>
        <lefthand value="0"/>
    </processing>

    <junctions>
        <no-turnarounds value="true"/>
        <junctions.corner-detail value="5"/>
        <junctions.limit-turn-speed value="5.50"/>
        <rectangular-lane-cut value="0"/>
    </junctions>

    <pedestrian>
        <walkingareas value="0"/>
    </pedestrian>

</neteditConfiguration>
-->

<edges version="1.20" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/edges_file.xsd">
    <edge id="-E44" from="J39" to="J38" priority="-1" numLanes="2" speed="13.89">
        <lane index="0" disallow="all"/>
        <lane index="1" allow="rail"/>
    </edge>
    <edge id="E44" from="J38" to="J39" priority="-1" numLanes="2" speed="13.89">
        <lane index="0" disallow="all"/>
        <lane index="1" allow="rail"/>
    </edge>
    <edge id="EdgeExternBot" from="JunctionExtern0" to="JunctionExtern1" priority="-1" numLanes="1" speed="13.89" shape="-60.00,0.00 -45.00,0.00 -45.00,-25.00 -40.00,-30.00 40.00,-30.00 45.00,-25.00 45.00,0.00 60.00,0.00" length="175.00" width="3.00" disallow="pedestrian"/>
    <edge id="EdgeExternTop" from="JunctionExtern1" to="JunctionExtern0" priority="-1" numLanes="1" speed="13.89" shape="60.00,0.00 45.00,0.00 45.00,25.00 40.00,30.00 -40.00,30.00 -45.00,25.00 -45.00,0.00 -60.00,0.00" length="175.00" width="3.00" disallow="pedestrian"/>
</edges>

=== eclipse-sumo/sumo/tests/netconvert/node_building/node_shape/minimal-shape/input_plain.edg.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2023-06-06 12:38:30 by Eclipse SUMO netconvert Version v1_17_0+0735-ed7251a
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/netconvertConfiguration.xsd">

    <input>
        <sumo-net-file value="net.net.xml"/>
    </input>

    <output>
        <plain-output-prefix value="input_plain"/>
    </output>

    <processing>
        <geometry.min-radius.fix.railways value="false"/>
        <geometry.max-grade.fix value="false"/>
        <offset.disable-normalization value="true"/>
        <lefthand value="0"/>
    </processing>

    <junctions>
        <no-turnarounds value="true"/>
        <junctions.corner-detail value="5"/>
        <junctions.limit-turn-speed value="5.50"/>
        <rectangular-lane-cut value="0"/>
    </junctions>

    <pedestrian>
        <walkingareas value="0"/>
    </pedestrian>

</configuration>
-->

<edges version="1.16" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/edges_file.xsd">
    <edge id="-E0" from="J1" to="J0" priority="-1" numLanes="1" speed="13.89" spreadType="center" allow="rail" bidi="E0"/>
    <edge id="-E1" from="J2" to="J1" priority="-1" numLanes="1" speed="13.89" spreadType="center" allow="rail" bidi="E1"/>
    <edge id="-E2" from="J1" to="J3" priority="-1" numLanes="1" speed="13.89" spreadType="center" allow="rail" bidi="E2"/>
    <edge id="-E3" from="J5" to="J4" priority="-1" numLanes="1" speed="13.89" spreadType="center" allow="rail" bidi="E3"/>
    <edge id="-E4" from="J6" to="J5" priority="-1" numLanes="1" speed="13.89" spreadType="center" allow="rail" bidi="E4"/>
    <edge id="-E5" from="J5" to="J7" priority="-1" numLanes="1" speed="13.89" spreadType="center" allow="rail" bidi="E5"/>
    <edge id="E0" from="J0" to="J1" priority="-1" numLanes="1" speed="13.89" spreadType="center" allow="rail" bidi="-E0"/>
    <edge id="E1" from="J1" to="J2" priority="-1" numLanes="1" speed="13.89" spreadType="center" allow="rail" bidi="-E1"/>
    <edge id="E2" from="J3" to="J1" priority="-1" numLanes="1" speed="13.89" spreadType="center" allow="rail" bidi="-E2"/>
    <edge id="E3" from="J4" to="J5" priority="-1" numLanes="1" speed="13.89" spreadType="center" allow="rail" bidi="-E3"/>
    <edge id="E4" from="J5" to="J6" priority="-1" numLanes="1" speed="13.89" spreadType="center" allow="rail" bidi="-E4"/>
    <edge id="E5" from="J7" to="J5" priority="-1" numLanes="1" speed="13.89" spreadType="center" allow="rail" bidi="-E5"/>
</edges>
