=== eclipse-sumo/sumo/data/xsd/net_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:include schemaLocation="tazTypes.xsd" />

    <xsd:element name="net" type="netType">
        <xsd:key name="edgeKey">
            <xsd:selector xpath="edge"/>
            <xsd:field xpath="@id"/>
        </xsd:key>
        <xsd:keyref name="edgeKeyRefFrom" refer="edgeKey">
            <xsd:selector xpath="connection"/>
            <xsd:field xpath="@from"/>
        </xsd:keyref>
        <xsd:keyref name="edgeKeyRefTo" refer="edgeKey">
            <xsd:selector xpath="connection"/>
            <xsd:field xpath="@to"/>
        </xsd:keyref>
    </xsd:element>

    <xsd:complexType name="netType">
        <xsd:sequence>
            <xsd:element name="location" type="locationType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="type" type="typeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="edge" type="edgeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="tlLogic" type="tlLogicType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="junction" type="junctionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="connection" type="connectionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="prohibition" type="prohibitionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="roundabout" type="roundaboutType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="taz" type="tazType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="version">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="\d+.\d+"></xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="junctionCornerDetail" type="xsd:int"/>
        <xsd:attribute name="junctionLinkDetail" type="xsd:int"/>
        <xsd:attribute name="lefthand" type="boolType"/>
        <xsd:attribute name="rectangularLaneCut" type="boolType"/>
        <xsd:attribute name="walkingareas" type="boolType"/>
        <xsd:attribute name="limitTurnSpeed" type="floatType"/>
        <xsd:attribute name="checkLaneFoesAll" type="boolType"/>
        <xsd:attribute name="checkLaneFoesRoundabout" type="boolType"/>
        <xsd:attribute name="tlsIgnoreInternalJunctionJam" type="boolType"/>
        <xsd:attribute name="spreadType" type="spreadTypeType"/>
        <xsd:attribute name="avoidOverlap" type="boolType"/>
        <xsd:attribute name="junctionHigherSpeed" type="boolType"/>
        <xsd:attribute name="internalJunctionsVehicleWidth" type="floatType"/>
        <xsd:attribute name="junctionsMinimalShape" type="boolType"/>
        <xsd:attribute name="junctionsEndpointShape" type="boolType"/>
    </xsd:complexType>

    <xsd:complexType name="edgeType">
        <xsd:choice  minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="lane" type="laneType" minOccurs="1" maxOccurs="63"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="stopOffset" type="stopOffsetType" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="function" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="normal"/>
                    <xsd:enumeration value="internal"/>
                    <xsd:enumeration value="connector"/>
                    <xsd:enumeration value="crossing"/>
                    <xsd:enumeration value="walkingarea"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="from" type="xsd:string"/>
        <xsd:attribute name="to" type="xsd:string"/>
        <xsd:attribute name="name" type="xsd:string" use="optional"/>
        <xsd:attribute name="priority" type="xsd:integer" use="optional"/>
        <xsd:attribute name="length" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="bidi" type="xsd:string" use="optional"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="shape" type="shapeTypeTwo" use="optional"/>
        <xsd:attribute name="distance" type="floatType"/>
        <xsd:attribute name="spreadType" type="spreadTypeType" use="optional"/>
        <xsd:attribute name="crossingEdges" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:simpleType name="spreadTypeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="center"/>
            <xsd:enumeration value="roadCenter"/>
            <xsd:enumeration value="right"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="laneType">
        <xsd:choice  minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="neigh" type="neighType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="stopOffset" type="stopOffsetType" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="index" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="allow" type="xsd:string" use="optional"/>
        <xsd:attribute name="disallow" type="xsd:string" use="optional"/>
        <xsd:attribute name="prefer" type="xsd:string" use="optional"/>
        <xsd:attribute name="speed" type="positiveFloatType" use="required"/>
        <xsd:attribute name="friction" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="length" type="positiveFloatType" use="required"/>
        <xsd:attribute name="endOffset" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="width" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="acceleration" type="boolType" use="optional"/>
        <xsd:attribute name="shape" type="shapeTypeTwo" use="required"/>
        <xsd:attribute name="customShape" type="boolType" use="optional"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="changeRight" type="xsd:string" use="optional"/>
        <xsd:attribute name="changeLeft" type="xsd:string" use="optional"/>
        <xsd:attribute name="outlineShape" type="shapeType" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="junctionType">
        <xsd:sequence>
            <xsd:element name="request" type="requestType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="x" type="floatType" use="required"/>
        <xsd:attribute name="y" type="floatType" use="required"/>
        <xsd:attribute name="z" type="floatType" use="optional"/>
        <xsd:attribute name="type" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="traffic_light"/>
                    <xsd:enumeration value="traffic_light_unregulated"/>
                    <xsd:enumeration value="traffic_light_right_on_red"/>
                    <xsd:enumeration value="rail_signal"/>
                    <xsd:enumeration value="rail_crossing"/>
                    <xsd:enumeration value="priority"/>
                    <xsd:enumeration value="priority_stop"/>
                    <xsd:enumeration value="left_before_right"/>
                    <xsd:enumeration value="right_before_left"/>
                    <xsd:enumeration value="allway_stop"/>
                    <xsd:enumeration value="zipper"/>
                    <xsd:enumeration value="district"/>
                    <xsd:enumeration value="unregulated"/>
                    <xsd:enumeration value="internal"/>
                    <xsd:enumeration value="dead_end"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="incLanes" type="xsd:string" use="required"/>
        <xsd:attribute name="intLanes" type="xsd:string" use="required"/>
        <xsd:attribute name="shape" type="shapeType" use="optional"/>
        <xsd:attribute name="name" type="xsd:string" use="optional"/>
        <xsd:attribute name="radius" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="customShape" type="boolType" use="optional"/>
        <xsd:attribute name="rightOfWay" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="default"/>
                    <xsd:enumeration value="mixedPriority"/>
                    <xsd:enumeration value="allwayStop"/>
                    <xsd:enumeration value="edgePriority"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="fringe" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="default"/>
                    <xsd:enumeration value="outer"/>
                    <xsd:enumeration value="inner"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="requestType">
        <xsd:attribute name="index" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="response" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="[01]+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="foes" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="[01]+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="cont" type="boolType" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="stopOffsetType">
        <xsd:attribute name="value" type="nonNegativeFloatType" use="required"/>
        <xsd:attribute name="vClasses" type="xsd:string" use="optional"/>
        <xsd:attribute name="exceptions" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="connectionType">
        <xsd:choice  minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="conflict" type="conflictType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="from" type="xsd:string" use="required"/>
        <xsd:attribute name="to" type="xsd:string" use="required"/>
        <xsd:attribute name="fromLane" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="toLane" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="pass" type="boolType" use="optional"/>
        <xsd:attribute name="keepClear" type="boolType" use="optional"/>
        <xsd:attribute name="contPos" type="floatType" use="optional"/>
        <xsd:attribute name="visibility" type="floatType" use="optional"/>
        <xsd:attribute name="allow" type="xsd:string" use="optional"/>
        <xsd:attribute name="disallow" type="xsd:string" use="optional"/>
        <xsd:attribute name="speed" type="floatType" use="optional"/>
        <xsd:attribute name="length" type="floatType" use="optional"/>
        <xsd:attribute name="shape" type="shapeType" use="optional"/>
        <xsd:attribute name="uncontrolled" type="boolType" use="optional"/>
        <xsd:attribute name="via" type="xsd:string" use="optional"/>
        <xsd:attribute name="tl" type="xsd:string" use="optional"/>
        <xsd:attribute name="linkIndex" type="xsd:integer" use="optional"/>
        <xsd:attribute name="linkIndex2" type="xsd:integer" use="optional"/>
        <xsd:attribute name="changeRight" type="xsd:string" use="optional"/>
        <xsd:attribute name="changeLeft" type="xsd:string" use="optional"/>
        <xsd:attribute name="indirect" type="boolType" use="optional"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="dir" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="s"/>
                    <xsd:enumeration value="t"/>
                    <xsd:enumeration value="T"/>
                    <xsd:enumeration value="l"/>
                    <xsd:enumeration value="r"/>
                    <xsd:enumeration value="L"/>
                    <xsd:enumeration value="R"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="state" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="M"/>
                    <xsd:enumeration value="m"/>
                    <xsd:enumeration value="O"/>
                    <xsd:enumeration value="o"/>
                    <xsd:enumeration value="="/>
                    <xsd:enumeration value="-"/>
                    <xsd:enumeration value="s"/>
                    <xsd:enumeration value="w"/>
                    <xsd:enumeration value="Z"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="prohibitionType">
        <xsd:attribute name="prohibitor" type="xsd:string" use="required"/>
        <xsd:attribute name="prohibited" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="roundaboutType">
        <xsd:attribute name="nodes" type="xsd:string" use="required"/>
        <xsd:attribute name="edges" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="neighType">
        <xsd:attribute name="lane" type="xsd:string" use="required"/>
    </xsd:complexType>

</xsd:schema>

=== eclipse-sumo/sumo/tests/tools/sumolib/getNeighboring/input_net.net.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2026-06-18T14:47:08.245863+01:00 by Eclipse SUMO netedit v1_27_0+0254-729049c22fc
<neteditConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/neteditConfiguration.xsd">

    <input>
        <sumo-net-file value="input_net.net.xml"/>
    </input>

    <output>
        <output-file value="input_net.net.xml"/>
    </output>

    <processing>
        <geometry.min-radius.fix.railways value="false"/>
        <geometry.avoid-overlap value="false"/>
        <geometry.max-grade.fix value="false"/>
        <offset.disable-normalization value="true"/>
    </processing>

    <junctions>
        <no-turnarounds value="true"/>
        <junctions.corner-detail value="0"/>
        <junctions.limit-turn-speed value="-1.00"/>
    </junctions>

</neteditConfiguration>
-->

<net version="1.20" avoidOverlap="0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">

    <location netOffset="100.00,100.00" convBoundary="100.00,0.00,200.00,200.00" origBoundary="-10000000000.00,-10000000000.00,10000000000.00,10000000000.00" projParameter="!"/>

    <edge id=":C_0" function="internal">
        <lane id=":C_0_0" index="0" speed="13.89" length="34.84" shape="104.80,73.60 106.15,83.05 110.20,89.80 116.95,93.85 126.40,95.20"/>
        <lane id=":C_0_1" index="1" speed="13.89" length="37.45" shape="104.80,73.60 106.15,84.45 110.20,92.20 116.95,96.85 126.40,98.40"/>
    </edge>
    <edge id=":C_2" function="internal">
        <lane id=":C_2_0" index="0" speed="13.89" length="46.40" shape="104.80,73.60 104.80,120.00"/>
        <lane id=":C_2_1" index="1" speed="13.89" length="46.40" shape="101.60,73.60 101.60,120.00"/>
    </edge>

    <edge id="CE" from="C" to="E" priority="2">
        <lane id="CE_0" index="0" speed="13.89" length="73.60" shape="126.40,95.20 200.00,95.20">
            <param key="lk1" value="lv1"/>
            <param key="lk2" value="lv2"/>
        </lane>
        <lane id="CE_1" index="1" speed="13.89" length="73.60" shape="126.40,98.40 200.00,98.40">
            <param key="lk3" value="lv3"/>
            <param key="lk4" value="lv4"/>
        </lane>
        <param key="ek1" value="ev1"/>
        <param key="ek2" value="ev2"/>
        <param key="ek3" value="ev3"/>
        <param key="ek4" value="ev4"/>
    </edge>
    <edge id="CN" from="C" to="N" priority="2">
        <lane id="CN_0" index="0" speed="13.89" length="80.00" shape="104.80,120.00 104.80,200.00"/>
        <lane id="CN_1" index="1" speed="13.89" length="80.00" shape="101.60,120.00 101.60,200.00"/>
    </edge>
    <edge id="NS" from="N" to="S" priority="-1">
        <lane id="NS_0" index="0" speed="13.89" length="200.00" shape="95.20,200.00 95.20,0.00"/>
        <lane id="NS_1" index="1" speed="13.89" length="200.00" shape="98.40,200.00 98.40,0.00"/>
    </edge>
    <edge id="SC" from="S" to="C" priority="2">
        <lane id="SC_0" index="0" speed="13.89" length="73.60" shape="104.80,0.00 104.80,73.60"/>
        <lane id="SC_1" index="1" speed="13.89" length="73.60" shape="101.60,0.00 101.60,73.60"/>
    </edge>

    <junction id="C" type="priority" x="100.00" y="100.00" incLanes="SC_0 SC_1" intLanes=":C_0_0 :C_0_1 :C_2_0 :C_2_1" shape="100.00,120.00 106.40,120.00 126.40,100.00 126.40,93.60 106.40,73.60 100.00,73.60" radius="20.00">
        <request index="0" response="0000" foes="0000" cont="0"/>
        <request index="1" response="0000" foes="0000" cont="0"/>
        <request index="2" response="0000" foes="0000" cont="0"/>
        <request index="3" response="0000" foes="0000" cont="0"/>
        <param key="jk1" value="jv1"/>
        <param key="jk2" value="jv2"/>
    </junction>
    <junction id="E" type="dead_end" x="200.00" y="100.00" incLanes="CE_0 CE_1" intLanes="" shape="200.00,93.60 200.00,100.00"/>
    <junction id="N" type="dead_end" x="100.00" y="200.00" incLanes="CN_0 CN_1" intLanes="" shape="100.00,200.00 106.40,200.00 100.00,200.00"/>
    <junction id="S" type="dead_end" x="100.00" y="0.00" incLanes="NS_0 NS_1" intLanes="" shape="100.00,0.00 93.60,0.00 100.00,0.00"/>

    <connection from="SC" to="CE" fromLane="0" toLane="0" via=":C_0_0" dir="r" state="M"/>
    <connection from="SC" to="CE" fromLane="0" toLane="1" via=":C_0_1" dir="r" state="M"/>
    <connection from="SC" to="CN" fromLane="0" toLane="0" via=":C_2_0" dir="s" state="M"/>
    <connection from="SC" to="CN" fromLane="1" toLane="1" via=":C_2_1" dir="s" state="M"/>

    <connection from=":C_0" to="CE" fromLane="0" toLane="0" dir="r" state="M"/>
    <connection from=":C_0" to="CE" fromLane="1" toLane="1" dir="r" state="M"/>
    <connection from=":C_2" to="CN" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":C_2" to="CN" fromLane="1" toLane="1" dir="s" state="M"/>

</net>

=== eclipse-sumo/sumo/tests/sumo/junction_model/visibility/with_sudden_foe/net.net.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on Di 08 Nov 2016 14:38:55 CET by Netedit Version dev-SVN-r21650
This data file and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
SPDX-License-Identifier: EPL-2.0
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/netedit.exeConfiguration.xsd">

    <input>
        <sumo-net-file value="net.net.xml"/>
    </input>

    <output>
        <output-file value="net.net.xml"/>
    </output>

    <processing>
        <no-internal-links value="false"/>
        <no-turnarounds value="true"/>
        <offset.disable-normalization value="true"/>
        <lefthand value="false"/>
        <junctions.corner-detail value="0"/>
    </processing>

</configuration>
-->

<net version="0.27" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">

    <location netOffset="0.00,0.00" convBoundary="0.00,-50.00,200.00,150.00" origBoundary="-10000000000.00,-10000000000.00,10000000000.00,10000000000.00" projParameter="!"/>

    <edge id=":C_0" function="internal">
        <lane id=":C_0_0" index="0" speed="13.89" length="5.00" shape="98.35,54.75 98.16,53.39 97.57,52.43 96.61,51.84 95.25,51.65"/>
    </edge>
    <edge id=":C_1" function="internal">
        <lane id=":C_1_0" index="0" speed="13.89" length="9.50" shape="98.35,54.75 98.35,45.25"/>
    </edge>
    <edge id=":C_2" function="internal">
        <lane id=":C_2_0" index="0" speed="13.89" length="5.28" shape="98.35,54.75 98.75,51.95 99.95,49.95 100.05,49.89"/>
    </edge>
    <edge id=":C_12" function="internal">
        <lane id=":C_12_0" index="0" speed="13.89" length="5.04" shape="100.05,49.89 101.95,48.75 104.75,48.35"/>
    </edge>
    <edge id=":C_3" function="internal">
        <lane id=":C_3_0" index="0" speed="13.89" length="5.00" shape="104.75,51.65 103.39,51.84 102.43,52.42 101.84,53.39 101.65,54.75"/>
    </edge>
    <edge id=":C_4" function="internal">
        <lane id=":C_4_0" index="0" speed="13.89" length="9.50" shape="104.75,51.65 95.25,51.65"/>
    </edge>
    <edge id=":C_5" function="internal">
        <lane id=":C_5_0" index="0" speed="13.89" length="10.32" shape="104.75,51.65 101.95,51.25 99.95,50.05 98.75,48.05 98.35,45.25"/>
    </edge>
    <edge id=":C_6" function="internal">
        <lane id=":C_6_0" index="0" speed="13.89" length="5.00" shape="101.65,45.25 101.84,46.61 102.43,47.57 103.39,48.16 104.75,48.35"/>
    </edge>
    <edge id=":C_7" function="internal">
        <lane id=":C_7_0" index="0" speed="13.89" length="9.50" shape="101.65,45.25 101.65,54.75"/>
    </edge>
    <edge id=":C_8" function="internal">
        <lane id=":C_8_0" index="0" speed="13.89" length="5.28" shape="101.65,45.25 101.25,48.05 100.05,50.05 99.95,50.11"/>
    </edge>
    <edge id=":C_13" function="internal">
        <lane id=":C_13_0" index="0" speed="13.89" length="5.04" shape="99.95,50.11 98.05,51.25 95.25,51.65"/>
    </edge>
    <edge id=":C_9" function="internal">
        <lane id=":C_9_0" index="0" speed="13.89" length="5.00" shape="95.25,48.35 96.61,48.16 97.57,47.58 98.16,46.61 98.35,45.25"/>
    </edge>
    <edge id=":C_10" function="internal">
        <lane id=":C_10_0" index="0" speed="13.89" length="9.50" shape="95.25,48.35 104.75,48.35"/>
    </edge>
    <edge id=":C_11" function="internal">
        <lane id=":C_11_0" index="0" speed="13.89" length="10.32" shape="95.25,48.35 98.05,48.75 100.05,49.95 101.25,51.95 101.65,54.75"/>
    </edge>

    <edge id="CE" from="C" to="E" priority="1">
        <lane id="CE_0" index="0" speed="13.89" length="95.25" shape="104.75,48.35 200.00,48.35"/>
    </edge>
    <edge id="CN" from="C" to="N" priority="2">
        <lane id="CN_0" index="0" speed="13.89" length="95.25" shape="101.65,54.75 101.65,150.00"/>
    </edge>
    <edge id="CS" from="C" to="S" priority="2">
        <lane id="CS_0" index="0" speed="13.89" length="95.25" shape="98.35,45.25 98.35,-50.00"/>
    </edge>
    <edge id="CW" from="C" to="W" priority="1">
        <lane id="CW_0" index="0" speed="13.89" length="95.25" shape="95.25,51.65 0.00,51.65"/>
    </edge>
    <edge id="EC" from="E" to="C" priority="1">
        <lane id="EC_0" index="0" speed="13.89" length="95.25" shape="200.00,51.65 104.75,51.65"/>
    </edge>
    <edge id="NC" from="N" to="C" priority="2">
        <lane id="NC_0" index="0" speed="13.89" length="95.25" shape="98.35,150.00 98.35,54.75"/>
    </edge>
    <edge id="SC" from="S" to="C" priority="2">
        <lane id="SC_0" index="0" speed="13.89" length="95.25" shape="101.65,-50.00 101.65,45.25"/>
    </edge>
    <edge id="WC" from="W" to="C" priority="1" type="roundabout">
        <lane id="WC_0" index="0" speed="13.89" length="95.25" shape="0.00,48.35 95.25,48.35"/>
    </edge>

    <junction id="C" type="priority" x="100.00" y="50.00" incLanes="NC_0 EC_0 SC_0 WC_0" intLanes=":C_0_0 :C_1_0 :C_12_0 :C_3_0 :C_4_0 :C_5_0 :C_6_0 :C_7_0 :C_13_0 :C_9_0 :C_10_0 :C_11_0" shape="96.75,54.75 103.25,54.75 104.75,53.25 104.75,46.75 103.25,45.25 96.75,45.25 95.25,46.75 95.25,53.25">
        <request index="0" response="000000000000" foes="000100010000" cont="0"/>
        <request index="1" response="000000000000" foes="111100110000" cont="0"/>
        <request index="2" response="000011000000" foes="110011110000" cont="1"/>
        <request index="3" response="000010000000" foes="100010000000" cont="0"/>
        <request index="4" response="000110000111" foes="100110000111" cont="0"/>
        <request index="5" response="011110000110" foes="011110000110" cont="0"/>
        <request index="6" response="000000000000" foes="010000000100" cont="0"/>
        <request index="7" response="000000000000" foes="110000111100" cont="0"/>
        <request index="8" response="000000000011" foes="110000110011" cont="1"/>
        <request index="9" response="000000000010" foes="000000100010" cont="0"/>
        <request index="10" response="000111000110" foes="000111100110" cont="0"/>
        <request index="11" response="000110011110" foes="000110011110" cont="0"/>
    </junction>
    <junction id="E" type="unregulated" x="200.00" y="50.00" incLanes="CE_0" intLanes="" shape="200.00,50.05 200.00,46.75 200.00,49.95"/>
    <junction id="N" type="unregulated" x="100.00" y="150.00" incLanes="CN_0" intLanes="" shape="99.95,150.00 103.25,150.00 100.05,150.00"/>
    <junction id="S" type="unregulated" x="100.00" y="-50.00" incLanes="CS_0" intLanes="" shape="100.05,-50.00 96.75,-50.00 99.95,-50.00"/>
    <junction id="W" type="unregulated" x="0.00" y="50.00" incLanes="CW_0" intLanes="" shape="0.00,49.95 0.00,53.25 0.00,50.05"/>

    <junction id=":C_12_0" type="internal" x="100.05" y="49.89" incLanes=":C_2_0 SC_0" intLanes=":C_4_0 :C_5_0 :C_6_0 :C_7_0 :C_10_0 :C_11_0"/>
    <junction id=":C_13_0" type="internal" x="99.95" y="50.11" incLanes=":C_8_0 NC_0" intLanes=":C_0_0 :C_1_0 :C_4_0 :C_5_0 :C_10_0 :C_11_0"/>

    <connection from="EC" to="CN" fromLane="0" toLane="0" via=":C_3_0" dir="r" state="m"/>
    <connection from="EC" to="CW" fromLane="0" toLane="0" via=":C_4_0" dir="s" state="m"/>
    <connection from="EC" to="CS" fromLane="0" toLane="0" via=":C_5_0" dir="l" state="m"/>
    <connection from="NC" to="CW" fromLane="0" toLane="0" via=":C_0_0" dir="r" state="M"/>
    <connection from="NC" to="CS" fromLane="0" toLane="0" via=":C_1_0" dir="s" state="M"/>
    <connection from="NC" to="CE" fromLane="0" toLane="0" via=":C_2_0" dir="l" state="m"/>
    <connection from="SC" to="CE" fromLane="0" toLane="0" via=":C_6_0" dir="r" state="M"/>
    <connection from="SC" to="CN" fromLane="0" toLane="0" via=":C_7_0" dir="s" state="M"/>
    <connection from="SC" to="CW" fromLane="0" toLane="0" via=":C_8_0" dir="l" state="m"/>
    <connection from="WC" to="CS" fromLane="0" toLane="0" via=":C_9_0" dir="r" state="m"/>
    <connection from="WC" to="CE" fromLane="0" toLane="0" visibility="100.00" via=":C_10_0" dir="s" state="m"/>
    <connection from="WC" to="CN" fromLane="0" toLane="0" via=":C_11_0" dir="l" state="m"/>

    <connection from=":C_0" to="CW" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":C_1" to="CS" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":C_2" to="CE" fromLane="0" toLane="0" via=":C_12_0" dir="s" state="m"/>
    <connection from=":C_12" to="CE" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":C_3" to="CN" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":C_4" to="CW" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":C_5" to="CS" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":C_6" to="CE" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":C_7" to="CN" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":C_8" to="CW" fromLane="0" toLane="0" via=":C_13_0" visibility="100.00" dir="s" state="m"/>
    <connection from=":C_13" to="CW" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":C_9" to="CS" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":C_10" to="CE" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from=":C_11" to="CN" fromLane="0" toLane="0" dir="s" state="M"/>

</net>
