=== eclipse-sumo/sumo/data/xsd/net_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:include schemaLocation="tazTypes.xsd" />

    <xsd:element name="net" type="netType">
        <xsd:key name="edgeKey">
            <xsd:selector xpath="edge"/>
            <xsd:field xpath="@id"/>
        </xsd:key>
        <xsd:keyref name="edgeKeyRefFrom" refer="edgeKey">
            <xsd:selector xpath="connection"/>
            <xsd:field xpath="@from"/>
        </xsd:keyref>
        <xsd:keyref name="edgeKeyRefTo" refer="edgeKey">
            <xsd:selector xpath="connection"/>
            <xsd:field xpath="@to"/>
        </xsd:keyref>
    </xsd:element>

    <xsd:complexType name="netType">
        <xsd:sequence>
            <xsd:element name="location" type="locationType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="type" type="typeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="edge" type="edgeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="tlLogic" type="tlLogicType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="junction" type="junctionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="connection" type="connectionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="prohibition" type="prohibitionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="roundabout" type="roundaboutType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="taz" type="tazType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="version">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="\d+.\d+"></xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="junctionCornerDetail" type="xsd:int"/>
        <xsd:attribute name="junctionLinkDetail" type="xsd:int"/>
        <xsd:attribute name="lefthand" type="boolType"/>
        <xsd:attribute name="rectangularLaneCut" type="boolType"/>
        <xsd:attribute name="walkingareas" type="boolType"/>
        <xsd:attribute name="limitTurnSpeed" type="floatType"/>
        <xsd:attribute name="checkLaneFoesAll" type="boolType"/>
        <xsd:attribute name="checkLaneFoesRoundabout" type="boolType"/>
        <xsd:attribute name="tlsIgnoreInternalJunctionJam" type="boolType"/>
        <xsd:attribute name="spreadType" type="spreadTypeType"/>
        <xsd:attribute name="avoidOverlap" type="boolType"/>
        <xsd:attribute name="junctionHigherSpeed" type="boolType"/>
        <xsd:attribute name="internalJunctionsVehicleWidth" type="floatType"/>
        <xsd:attribute name="junctionsMinimalShape" type="boolType"/>
        <xsd:attribute name="junctionsEndpointShape" type="boolType"/>
    </xsd:complexType>

    <xsd:complexType name="edgeType">
        <xsd:choice  minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="lane" type="laneType" minOccurs="1" maxOccurs="63"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="stopOffset" type="stopOffsetType" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="function" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="normal"/>
                    <xsd:enumeration value="internal"/>
                    <xsd:enumeration value="connector"/>
                    <xsd:enumeration value="crossing"/>
                    <xsd:enumeration value="walkingarea"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="from" type="xsd:string"/>
        <xsd:attribute name="to" type="xsd:string"/>
        <xsd:attribute name="name" type="xsd:string" use="optional"/>
        <xsd:attribute name="priority" type="xsd:integer" use="optional"/>
        <xsd:attribute name="length" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="bidi" type="xsd:string" use="optional"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="shape" type="shapeTypeTwo" use="optional"/>
        <xsd:attribute name="distance" type="floatType"/>
        <xsd:attribute name="spreadType" type="spreadTypeType" use="optional"/>
        <xsd:attribute name="crossingEdges" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:simpleType name="spreadTypeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="center"/>
            <xsd:enumeration value="roadCenter"/>
            <xsd:enumeration value="right"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="laneType">
        <xsd:choice  minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="neigh" type="neighType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="stopOffset" type="stopOffsetType" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="index" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="allow" type="xsd:string" use="optional"/>
        <xsd:attribute name="disallow" type="xsd:string" use="optional"/>
        <xsd:attribute name="prefer" type="xsd:string" use="optional"/>
        <xsd:attribute name="speed" type="positiveFloatType" use="required"/>
        <xsd:attribute name="friction" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="length" type="positiveFloatType" use="required"/>
        <xsd:attribute name="endOffset" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="width" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="acceleration" type="boolType" use="optional"/>
        <xsd:attribute name="shape" type="shapeTypeTwo" use="required"/>
        <xsd:attribute name="customShape" type="boolType" use="optional"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="changeRight" type="xsd:string" use="optional"/>
        <xsd:attribute name="changeLeft" type="xsd:string" use="optional"/>
        <xsd:attribute name="outlineShape" type="shapeType" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="junctionType">
        <xsd:sequence>
            <xsd:element name="request" type="requestType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="x" type="floatType" use="required"/>
        <xsd:attribute name="y" type="floatType" use="required"/>
        <xsd:attribute name="z" type="floatType" use="optional"/>
        <xsd:attribute name="type" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="traffic_light"/>
                    <xsd:enumeration value="traffic_light_unregulated"/>
                    <xsd:enumeration value="traffic_light_right_on_red"/>
                    <xsd:enumeration value="rail_signal"/>
                    <xsd:enumeration value="rail_crossing"/>
                    <xsd:enumeration value="priority"/>
                    <xsd:enumeration value="priority_stop"/>
                    <xsd:enumeration value="left_before_right"/>
                    <xsd:enumeration value="right_before_left"/>
                    <xsd:enumeration value="allway_stop"/>
                    <xsd:enumeration value="zipper"/>
                    <xsd:enumeration value="district"/>
                    <xsd:enumeration value="unregulated"/>
                    <xsd:enumeration value="internal"/>
                    <xsd:enumeration value="dead_end"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="incLanes" type="xsd:string" use="required"/>
        <xsd:attribute name="intLanes" type="xsd:string" use="required"/>
        <xsd:attribute name="shape" type="shapeType" use="optional"/>
        <xsd:attribute name="name" type="xsd:string" use="optional"/>
        <xsd:attribute name="radius" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="customShape" type="boolType" use="optional"/>
        <xsd:attribute name="rightOfWay" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="default"/>
                    <xsd:enumeration value="mixedPriority"/>
                    <xsd:enumeration value="allwayStop"/>
                    <xsd:enumeration value="edgePriority"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="fringe" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="default"/>
                    <xsd:enumeration value="outer"/>
                    <xsd:enumeration value="inner"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="requestType">
        <xsd:attribute name="index" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="response" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="[01]+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="foes" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="[01]+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="cont" type="boolType" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="stopOffsetType">
        <xsd:attribute name="value" type="nonNegativeFloatType" use="required"/>
        <xsd:attribute name="vClasses" type="xsd:string" use="optional"/>
        <xsd:attribute name="exceptions" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="connectionType">
        <xsd:choice  minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="conflict" type="conflictType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="from" type="xsd:string" use="required"/>
        <xsd:attribute name="to" type="xsd:string" use="required"/>
        <xsd:attribute name="fromLane" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="toLane" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="pass" type="boolType" use="optional"/>
        <xsd:attribute name="keepClear" type="boolType" use="optional"/>
        <xsd:attribute name="contPos" type="floatType" use="optional"/>
        <xsd:attribute name="visibility" type="floatType" use="optional"/>
        <xsd:attribute name="allow" type="xsd:string" use="optional"/>
        <xsd:attribute name="disallow" type="xsd:string" use="optional"/>
        <xsd:attribute name="speed" type="floatType" use="optional"/>
        <xsd:attribute name="length" type="floatType" use="optional"/>
        <xsd:attribute name="shape" type="shapeType" use="optional"/>
        <xsd:attribute name="uncontrolled" type="boolType" use="optional"/>
        <xsd:attribute name="via" type="xsd:string" use="optional"/>
        <xsd:attribute name="tl" type="xsd:string" use="optional"/>
        <xsd:attribute name="linkIndex" type="xsd:integer" use="optional"/>
        <xsd:attribute name="linkIndex2" type="xsd:integer" use="optional"/>
        <xsd:attribute name="changeRight" type="xsd:string" use="optional"/>
        <xsd:attribute name="changeLeft" type="xsd:string" use="optional"/>
        <xsd:attribute name="indirect" type="boolType" use="optional"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="dir" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="s"/>
                    <xsd:enumeration value="t"/>
                    <xsd:enumeration value="T"/>
                    <xsd:enumeration value="l"/>
                    <xsd:enumeration value="r"/>
                    <xsd:enumeration value="L"/>
                    <xsd:enumeration value="R"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="state" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="M"/>
                    <xsd:enumeration value="m"/>
                    <xsd:enumeration value="O"/>
                    <xsd:enumeration value="o"/>
                    <xsd:enumeration value="="/>
                    <xsd:enumeration value="-"/>
                    <xsd:enumeration value="s"/>
                    <xsd:enumeration value="w"/>
                    <xsd:enumeration value="Z"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="prohibitionType">
        <xsd:attribute name="prohibitor" type="xsd:string" use="required"/>
        <xsd:attribute name="prohibited" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="roundaboutType">
        <xsd:attribute name="nodes" type="xsd:string" use="required"/>
        <xsd:attribute name="edges" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="neighType">
        <xsd:attribute name="lane" type="xsd:string" use="required"/>
    </xsd:complexType>

</xsd:schema>

=== eclipse-sumo/sumo/tests/netedit/network/lanes/select_vtypes/allowed/scooter/net.net.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2024-07-01 08:55:57 by Eclipse SUMO netconvert Version v1_20_0+1067-ecd6dc8927e
This data file and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
This file may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License 2.0 are satisfied: GNU General Public License, version 2
or later which is available at
https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html
SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later
<netconvertConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/netconvertConfiguration.xsd">

    <input>
        <node-files value=".\netedit\network\lanes\select_vtypes\allowed\scooter\net.nod.xml"/>
        <edge-files value=".\netedit\network\lanes\select_vtypes\allowed\scooter\net.edg.xml"/>
        <connection-files value=".\netedit\network\lanes\select_vtypes\allowed\scooter\net.con.xml"/>
    </input>

    <output>
        <write-license value="true"/>
        <output-file value=".\netedit\network\lanes\select_vtypes\allowed\scooter\net.net.xml"/>
    </output>

    <processing>
        <offset.disable-normalization value="true"/>
    </processing>

    <report>
        <verbose value="true"/>
    </report>

</netconvertConfiguration>
-->

<net version="1.20" junctionCornerDetail="5" limitTurnSpeed="5.50" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">

    <location netOffset="0.00,0.00" convBoundary="-60.00,-30.00,60.00,30.00" origBoundary="-60.00,-30.00,60.00,30.00" projParameter="!"/>

    <edge id=":J38_0" function="internal">
        <lane id=":J38_0_0" index="0" allow="scooter" speed="3.65" length="4.67" shape="-35.00,1.60 -36.20,0.80 -36.60,0.00 -36.20,-0.80 -35.00,-1.60"/>
    </edge>
    <edge id=":J39_0" function="internal">
        <lane id=":J39_0_0" index="0" allow="scooter" speed="3.65" length="4.67" shape="35.00,-1.60 36.20,-0.80 36.60,0.00 36.20,0.80 35.00,1.60"/>
    </edge>
    <edge id=":JunctionExtern0_0" function="internal">
        <lane id=":JunctionExtern0_0_0" index="0" disallow="pedestrian" speed="3.53" length="4.38" width="3.00" shape="-60.00,1.50 -61.12,0.75 -61.50,0.00 -61.12,-0.75 -60.00,-1.50"/>
    </edge>
    <edge id=":JunctionExtern1_0" function="internal">
        <lane id=":JunctionExtern1_0_0" index="0" disallow="pedestrian" speed="3.53" length="4.38" width="3.00" shape="60.00,-1.50 61.12,-0.75 61.50,0.00 61.12,0.75 60.00,1.50"/>
    </edge>

    <edge id="-E44" from="J39" to="J38" priority="-1">
        <lane id="-E44_0" index="0" disallow="all" speed="13.89" length="70.00" shape="35.00,4.80 -35.00,4.80"/>
        <lane id="-E44_1" index="1" allow="scooter" speed="13.89" length="70.00" shape="35.00,1.60 -35.00,1.60"/>
    </edge>
    <edge id="E44" from="J38" to="J39" priority="-1">
        <lane id="E44_0" index="0" disallow="all" speed="13.89" length="70.00" shape="-35.00,-4.80 35.00,-4.80"/>
        <lane id="E44_1" index="1" allow="scooter" speed="13.89" length="70.00" shape="-35.00,-1.60 35.00,-1.60"/>
    </edge>
    <edge id="EdgeExternBot" from="JunctionExtern0" to="JunctionExtern1" priority="-1" length="175.00" shape="-60.00,0.00 -45.00,0.00 -45.00,-25.00 -40.00,-30.00 40.00,-30.00 45.00,-25.00 45.00,0.00 60.00,0.00">
        <lane id="EdgeExternBot_0" index="0" disallow="pedestrian" speed="13.89" length="175.00" width="3.00" shape="-60.00,-1.50 -46.50,-1.50 -46.50,-25.62 -40.62,-31.50 40.62,-31.50 46.50,-25.62 46.50,-1.50 60.00,-1.50"/>
    </edge>
    <edge id="EdgeExternTop" from="JunctionExtern1" to="JunctionExtern0" priority="-1" length="175.00" shape="60.00,0.00 45.00,0.00 45.00,25.00 40.00,30.00 -40.00,30.00 -45.00,25.00 -45.00,0.00 -60.00,0.00">
        <lane id="EdgeExternTop_0" index="0" disallow="pedestrian" speed="13.89" length="175.00" width="3.00" shape="60.00,1.50 46.50,1.50 46.50,25.62 40.62,31.50 -40.62,31.50 -46.50,25.62 -46.50,1.50 -60.00,1.50"/>
    </edge>

    <junction id="J38" type="priority" x="-35.00" y="0.00" incLanes="-E44_0 -E44_1" intLanes=":J38_0_0" shape="-35.00,0.00 -35.00,3.20 -35.00,0.00">
        <request index="0" response="0" foes="0" cont="0"/>
    </junction>
    <junction id="J39" type="priority" x="35.00" y="0.00" incLanes="E44_0 E44_1" intLanes=":J39_0_0" shape="35.00,0.00 35.00,-3.20 35.00,0.00">
        <request index="0" response="0" foes="0" cont="0"/>
    </junction>
    <junction id="JunctionExtern0" type="priority" x="-60.00" y="0.00" incLanes="EdgeExternTop_0" intLanes=":JunctionExtern0_0_0" shape="-60.00,0.00 -60.00,3.00 -60.00,0.00">
        <request index="0" response="0" foes="0" cont="0"/>
    </junction>
    <junction id="JunctionExtern1" type="priority" x="60.00" y="0.00" incLanes="EdgeExternBot_0" intLanes=":JunctionExtern1_0_0" shape="60.00,0.00 60.00,-3.00 60.00,0.00">
        <request index="0" response="0" foes="0" cont="0"/>
    </junction>

    <connection from="-E44" to="E44" fromLane="1" toLane="1" via=":J38_0_0" dir="t" state="M"/>
    <connection from="E44" to="-E44" fromLane="1" toLane="1" via=":J39_0_0" dir="t" state="M"/>
    <connection from="EdgeExternBot" to="EdgeExternTop" fromLane="0" toLane="0" via=":JunctionExtern1_0_0" dir="t" state="M"/>
    <connection from="EdgeExternTop" to="EdgeExternBot" fromLane="0" toLane="0" via=":JunctionExtern0_0_0" dir="t" state="M"/>

    <connection from=":J38_0" to="E44" fromLane="0" toLane="1" dir="t" state="M"/>
    <connection from=":J39_0" to="-E44" fromLane="0" toLane="1" dir="t" state="M"/>
    <connection from=":JunctionExtern0_0" to="EdgeExternBot" fromLane="0" toLane="0" dir="t" state="M"/>
    <connection from=":JunctionExtern1_0" to="EdgeExternTop" fromLane="0" toLane="0" dir="t" state="M"/>

</net>

=== eclipse-sumo/sumo/tests/sumo/opposite_direction_driving/network_problems/neigh_inconsistent2/net.net.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2025-07-16 13:37:11 by Eclipse SUMO netedit Version v1_23_1+1110-3ee544734de
<neteditConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/neteditConfiguration.xsd">

    <input>
        <sumo-net-file value="net.net.xml"/>
    </input>

    <output>
        <output-file value="net.net.xml"/>
    </output>

    <processing>
        <geometry.min-radius.fix.railways value="false"/>
        <geometry.avoid-overlap value="false"/>
        <geometry.max-grade.fix value="false"/>
        <offset.disable-normalization value="true"/>
        <lefthand value="0"/>
    </processing>

    <junctions>
        <no-internal-links value="true"/>
        <no-turnarounds value="true"/>
        <junctions.corner-detail value="5"/>
        <junctions.limit-turn-speed value="5.50"/>
        <rectangular-lane-cut value="0"/>
    </junctions>

    <pedestrian>
        <walkingareas value="0"/>
    </pedestrian>

</neteditConfiguration>
-->

<net version="1.20" junctionCornerDetail="5" limitTurnSpeed="5.50" avoidOverlap="0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">

    <location netOffset="0.00,0.00" convBoundary="0.00,0.00,100.00,0.00" origBoundary="-10000000000.00,-10000000000.00,10000000000.00,10000000000.00" projParameter="!"/>

    <edge id="-E0" from="J1" to="J0" priority="-1">
        <lane id="-E0_0" index="0" speed="13.89" length="100.00" shape="100.00,1.60 0.00,1.60">
            <neigh lane="E1_0"/>
        </lane>
    </edge>
    <edge id="E0" from="J0" to="J1" priority="-1">
        <lane id="E0_0" index="0" speed="13.89" length="100.00" shape="0.00,-1.60 100.00,-1.60">
            <neigh lane="-E0_0"/>
        </lane>
    </edge>
    <edge id="E1" from="J0" to="J1" priority="-1">
        <lane id="E1_0" index="0" speed="13.89" length="100.00" shape="0.00,-1.60 100.00,-1.60">
            <neigh lane="-E0_0"/>
        </lane>
    </edge>

    <junction id="J0" type="priority" x="0.00" y="0.00" incLanes="-E0_0" intLanes="" shape="0.00,0.00 0.00,3.20 0.00,-3.20">
        <request index="0" response="0" foes="0"/>
    </junction>
    <junction id="J1" type="priority" x="100.00" y="0.00" incLanes="E1_0 E0_0" intLanes="" shape="100.00,-3.20 100.00,3.20 100.00,0.00">
        <request index="0" response="0" foes="0"/>
    </junction>

    <connection from="-E0" to="E1" fromLane="0" toLane="0" dir="t" state="M"/>
    <connection from="E1" to="-E0" fromLane="0" toLane="0" dir="t" state="M"/>

</net>

=== eclipse-sumo/sumo/tests/netedit/netElements/edges/move/selected_separated/input_net.net.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on Tue Feb 19 09:11:19 2019 by Eclipse SUMO netconvert Version v1_1_0+0919-80296dbfce
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/netconvertConfiguration.xsd">

    <input>
        <node-files value=".\netedit\netElements\edges\move\selected_separated\input_net.nod.xml"/>
        <edge-files value=".\netedit\netElements\edges\move\selected_separated\input_net.edg.xml"/>
        <connection-files value=".\netedit\netElements\edges\move\selected_separated\input_net.con.xml"/>
        <tllogic-files value=".\netedit\netElements\edges\move\selected_separated\input_net.tll.xml"/>
    </input>

    <output>
        <output-file value=".\netedit\netElements\edges\move\selected_separated\input_net.net.xml"/>
    </output>

    <report>
        <verbose value="true"/>
    </report>

</configuration>
-->

<net version="1.1" junctionCornerDetail="5" limitTurnSpeed="5.50" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">

    <location netOffset="25.00,11.00" convBoundary="0.00,0.00,50.00,22.00" origBoundary="-10000000000.00,-10000000000.00,10000000000.00,10000000000.00" projParameter="!"/>

    <edge id=":gneJ0_0" function="internal">
        <lane id=":gneJ0_0_0" index="0" speed="3.65" length="4.67" shape="0.00,12.60 -1.20,11.80 -1.60,11.00 -1.20,10.20 0.00,9.40"/>
    </edge>
    <edge id=":gneJ1_0" function="internal">
        <lane id=":gneJ1_0_0" index="0" speed="3.65" length="4.67" shape="50.00,9.40 51.20,10.20 51.60,11.00 51.20,11.80 50.00,12.60"/>
    </edge>

    <edge id="gneE0" from="gneJ0" to="gneJ1" priority="1">
        <lane id="gneE0_0" index="0" speed="13.89" length="50.00" shape="0.00,9.40 50.00,9.40"/>
    </edge>
    <edge id="gneE1" from="gneJ1" to="gneJ0" priority="1">
        <lane id="gneE1_0" index="0" speed="13.89" length="50.00" shape="50.00,12.60 0.00,12.60"/>
    </edge>
    <edge id="gneE3" from="gneJ4" to="gneJ5" priority="-1">
        <lane id="gneE3_0" index="0" speed="13.89" length="49.00" shape="0.00,-1.60 49.00,-1.60"/>
    </edge>
    <edge id="gneE4" from="gneJ3" to="gneJ2" priority="-1">
        <lane id="gneE4_0" index="0" speed="13.89" length="50.00" shape="50.00,23.60 0.00,23.60"/>
    </edge>

    <tlLogic id="gneJ0" type="static" programID="0" offset="0">
        <phase duration="87" state="G"/>
        <phase duration="3"  state="y"/>
    </tlLogic>
    <tlLogic id="gneJ1" type="static" programID="0" offset="0">
        <phase duration="87" state="G"/>
        <phase duration="3"  state="y"/>
    </tlLogic>

    <junction id="gneJ0" type="traffic_light" x="0.00" y="11.00" incLanes="gneE1_0" intLanes=":gneJ0_0_0" shape="0.00,11.00 0.00,14.20 0.00,11.00">
        <request index="0" response="0" foes="0" cont="0"/>
    </junction>
    <junction id="gneJ1" type="traffic_light" x="50.00" y="11.00" incLanes="gneE0_0" intLanes=":gneJ1_0_0" shape="50.00,11.00 50.00,7.80 50.00,11.00">
        <request index="0" response="0" foes="0" cont="0"/>
    </junction>
    <junction id="gneJ2" type="dead_end" x="0.00" y="22.00" incLanes="gneE4_0" intLanes="" shape="0.00,25.20 0.00,22.00"/>
    <junction id="gneJ3" type="dead_end" x="50.00" y="22.00" incLanes="" intLanes="" shape="50.00,22.00 50.00,25.20"/>
    <junction id="gneJ4" type="dead_end" x="0.00" y="0.00" incLanes="" intLanes="" shape="0.00,0.00 0.00,-3.20"/>
    <junction id="gneJ5" type="dead_end" x="49.00" y="0.00" incLanes="gneE3_0" intLanes="" shape="49.00,-3.20 49.00,0.00"/>

    <connection from="gneE0" to="gneE1" fromLane="0" toLane="0" via=":gneJ1_0_0" tl="gneJ1" linkIndex="0" dir="t" state="O"/>
    <connection from="gneE1" to="gneE0" fromLane="0" toLane="0" via=":gneJ0_0_0" tl="gneJ0" linkIndex="0" dir="t" state="O"/>

    <connection from=":gneJ0_0" to="gneE0" fromLane="0" toLane="0" dir="t" state="M"/>
    <connection from=":gneJ1_0" to="gneE1" fromLane="0" toLane="0" dir="t" state="M"/>

</net>
