=== eclipse-sumo/sumo/data/xsd/net_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:include schemaLocation="tazTypes.xsd" />

    <xsd:element name="net" type="netType">
        <xsd:key name="edgeKey">
            <xsd:selector xpath="edge"/>
            <xsd:field xpath="@id"/>
        </xsd:key>
        <xsd:keyref name="edgeKeyRefFrom" refer="edgeKey">
            <xsd:selector xpath="connection"/>
            <xsd:field xpath="@from"/>
        </xsd:keyref>
        <xsd:keyref name="edgeKeyRefTo" refer="edgeKey">
            <xsd:selector xpath="connection"/>
            <xsd:field xpath="@to"/>
        </xsd:keyref>
    </xsd:element>

    <xsd:complexType name="netType">
        <xsd:sequence>
            <xsd:element name="location" type="locationType" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="type" type="typeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="edge" type="edgeType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="tlLogic" type="tlLogicType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="junction" type="junctionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="connection" type="connectionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="prohibition" type="prohibitionType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="roundabout" type="roundaboutType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="taz" type="tazType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="version">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="\d+.\d+"></xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="junctionCornerDetail" type="xsd:int"/>
        <xsd:attribute name="junctionLinkDetail" type="xsd:int"/>
        <xsd:attribute name="lefthand" type="boolType"/>
        <xsd:attribute name="rectangularLaneCut" type="boolType"/>
        <xsd:attribute name="walkingareas" type="boolType"/>
        <xsd:attribute name="limitTurnSpeed" type="floatType"/>
        <xsd:attribute name="checkLaneFoesAll" type="boolType"/>
        <xsd:attribute name="checkLaneFoesRoundabout" type="boolType"/>
        <xsd:attribute name="tlsIgnoreInternalJunctionJam" type="boolType"/>
        <xsd:attribute name="spreadType" type="spreadTypeType"/>
        <xsd:attribute name="avoidOverlap" type="boolType"/>
        <xsd:attribute name="junctionHigherSpeed" type="boolType"/>
        <xsd:attribute name="internalJunctionsVehicleWidth" type="floatType"/>
        <xsd:attribute name="junctionsMinimalShape" type="boolType"/>
        <xsd:attribute name="junctionsEndpointShape" type="boolType"/>
    </xsd:complexType>

    <xsd:complexType name="edgeType">
        <xsd:choice  minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="lane" type="laneType" minOccurs="1" maxOccurs="63"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="stopOffset" type="stopOffsetType" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="function" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="normal"/>
                    <xsd:enumeration value="internal"/>
                    <xsd:enumeration value="connector"/>
                    <xsd:enumeration value="crossing"/>
                    <xsd:enumeration value="walkingarea"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="from" type="xsd:string"/>
        <xsd:attribute name="to" type="xsd:string"/>
        <xsd:attribute name="name" type="xsd:string" use="optional"/>
        <xsd:attribute name="priority" type="xsd:integer" use="optional"/>
        <xsd:attribute name="length" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="bidi" type="xsd:string" use="optional"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="shape" type="shapeTypeTwo" use="optional"/>
        <xsd:attribute name="distance" type="floatType"/>
        <xsd:attribute name="spreadType" type="spreadTypeType" use="optional"/>
        <xsd:attribute name="crossingEdges" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:simpleType name="spreadTypeType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="center"/>
            <xsd:enumeration value="roadCenter"/>
            <xsd:enumeration value="right"/>
        </xsd:restriction>
    </xsd:simpleType>

    <xsd:complexType name="laneType">
        <xsd:choice  minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="neigh" type="neighType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="stopOffset" type="stopOffsetType" minOccurs="0" maxOccurs="1"/>
        </xsd:choice>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="index" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="allow" type="xsd:string" use="optional"/>
        <xsd:attribute name="disallow" type="xsd:string" use="optional"/>
        <xsd:attribute name="prefer" type="xsd:string" use="optional"/>
        <xsd:attribute name="speed" type="positiveFloatType" use="required"/>
        <xsd:attribute name="friction" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="length" type="positiveFloatType" use="required"/>
        <xsd:attribute name="endOffset" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="width" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="acceleration" type="boolType" use="optional"/>
        <xsd:attribute name="shape" type="shapeTypeTwo" use="required"/>
        <xsd:attribute name="customShape" type="boolType" use="optional"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="changeRight" type="xsd:string" use="optional"/>
        <xsd:attribute name="changeLeft" type="xsd:string" use="optional"/>
        <xsd:attribute name="outlineShape" type="shapeType" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="junctionType">
        <xsd:sequence>
            <xsd:element name="request" type="requestType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="idType" use="required"/>
        <xsd:attribute name="x" type="floatType" use="required"/>
        <xsd:attribute name="y" type="floatType" use="required"/>
        <xsd:attribute name="z" type="floatType" use="optional"/>
        <xsd:attribute name="type" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="traffic_light"/>
                    <xsd:enumeration value="traffic_light_unregulated"/>
                    <xsd:enumeration value="traffic_light_right_on_red"/>
                    <xsd:enumeration value="rail_signal"/>
                    <xsd:enumeration value="rail_crossing"/>
                    <xsd:enumeration value="priority"/>
                    <xsd:enumeration value="priority_stop"/>
                    <xsd:enumeration value="left_before_right"/>
                    <xsd:enumeration value="right_before_left"/>
                    <xsd:enumeration value="allway_stop"/>
                    <xsd:enumeration value="zipper"/>
                    <xsd:enumeration value="district"/>
                    <xsd:enumeration value="unregulated"/>
                    <xsd:enumeration value="internal"/>
                    <xsd:enumeration value="dead_end"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="incLanes" type="xsd:string" use="required"/>
        <xsd:attribute name="intLanes" type="xsd:string" use="required"/>
        <xsd:attribute name="shape" type="shapeType" use="optional"/>
        <xsd:attribute name="name" type="xsd:string" use="optional"/>
        <xsd:attribute name="radius" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="customShape" type="boolType" use="optional"/>
        <xsd:attribute name="rightOfWay" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="default"/>
                    <xsd:enumeration value="mixedPriority"/>
                    <xsd:enumeration value="allwayStop"/>
                    <xsd:enumeration value="edgePriority"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="fringe" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="default"/>
                    <xsd:enumeration value="outer"/>
                    <xsd:enumeration value="inner"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="requestType">
        <xsd:attribute name="index" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="response" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="[01]+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="foes" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern
                        value="[01]+">
                    </xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="cont" type="boolType" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="stopOffsetType">
        <xsd:attribute name="value" type="nonNegativeFloatType" use="required"/>
        <xsd:attribute name="vClasses" type="xsd:string" use="optional"/>
        <xsd:attribute name="exceptions" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="connectionType">
        <xsd:choice  minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xsd:element name="conflict" type="conflictType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:choice>
        <xsd:attribute name="from" type="xsd:string" use="required"/>
        <xsd:attribute name="to" type="xsd:string" use="required"/>
        <xsd:attribute name="fromLane" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="toLane" type="xsd:nonNegativeInteger" use="required"/>
        <xsd:attribute name="pass" type="boolType" use="optional"/>
        <xsd:attribute name="keepClear" type="boolType" use="optional"/>
        <xsd:attribute name="contPos" type="floatType" use="optional"/>
        <xsd:attribute name="visibility" type="floatType" use="optional"/>
        <xsd:attribute name="allow" type="xsd:string" use="optional"/>
        <xsd:attribute name="disallow" type="xsd:string" use="optional"/>
        <xsd:attribute name="speed" type="floatType" use="optional"/>
        <xsd:attribute name="length" type="floatType" use="optional"/>
        <xsd:attribute name="shape" type="shapeType" use="optional"/>
        <xsd:attribute name="uncontrolled" type="boolType" use="optional"/>
        <xsd:attribute name="via" type="xsd:string" use="optional"/>
        <xsd:attribute name="tl" type="xsd:string" use="optional"/>
        <xsd:attribute name="linkIndex" type="xsd:integer" use="optional"/>
        <xsd:attribute name="linkIndex2" type="xsd:integer" use="optional"/>
        <xsd:attribute name="changeRight" type="xsd:string" use="optional"/>
        <xsd:attribute name="changeLeft" type="xsd:string" use="optional"/>
        <xsd:attribute name="indirect" type="boolType" use="optional"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="dir" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="s"/>
                    <xsd:enumeration value="t"/>
                    <xsd:enumeration value="T"/>
                    <xsd:enumeration value="l"/>
                    <xsd:enumeration value="r"/>
                    <xsd:enumeration value="L"/>
                    <xsd:enumeration value="R"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="state" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="M"/>
                    <xsd:enumeration value="m"/>
                    <xsd:enumeration value="O"/>
                    <xsd:enumeration value="o"/>
                    <xsd:enumeration value="="/>
                    <xsd:enumeration value="-"/>
                    <xsd:enumeration value="s"/>
                    <xsd:enumeration value="w"/>
                    <xsd:enumeration value="Z"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="prohibitionType">
        <xsd:attribute name="prohibitor" type="xsd:string" use="required"/>
        <xsd:attribute name="prohibited" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="roundaboutType">
        <xsd:attribute name="nodes" type="xsd:string" use="required"/>
        <xsd:attribute name="edges" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="neighType">
        <xsd:attribute name="lane" type="xsd:string" use="required"/>
    </xsd:complexType>

</xsd:schema>

=== eclipse-sumo/sumo/tests/sumo/rail/rail_signal/driveway_variants/net.net.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2024-09-20 11:51:48 by Eclipse SUMO netedit Version v1_20_0+2084-215f6555307
<neteditConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/neteditConfiguration.xsd">

    <input>
        <sumo-net-file value="net.net.xml"/>
    </input>

    <output>
        <output-file value="net.net.xml"/>
        <output.street-names value="true"/>
    </output>

    <processing>
        <geometry.min-radius.fix.railways value="false"/>
        <geometry.max-grade.fix value="false"/>
        <offset.disable-normalization value="true"/>
        <lefthand value="0"/>
    </processing>

    <junctions>
        <no-internal-links value="true"/>
        <no-turnarounds value="true"/>
        <junctions.corner-detail value="5"/>
        <junctions.limit-turn-speed value="5.50"/>
        <rectangular-lane-cut value="0"/>
    </junctions>

    <pedestrian>
        <walkingareas value="0"/>
    </pedestrian>

</neteditConfiguration>
-->

<net version="1.20" junctionCornerDetail="5" limitTurnSpeed="5.50" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/net_file.xsd">

    <location netOffset="0.00,0.00" convBoundary="-100.00,0.00,500.00,100.00" origBoundary="-10000000000.00,-10000000000.00,10000000000.00,10000000000.00" projParameter="!"/>

    <edge id="-E0" from="J1" to="J0" priority="-1" spreadType="center" bidi="E0">
        <lane id="-E0_0" index="0" allow="rail" speed="13.89" length="100.00" shape="-5.36,0.00 -100.00,0.00"/>
    </edge>
    <edge id="-E1" from="J2" to="J1" priority="-1" spreadType="center" bidi="E1">
        <lane id="-E1_0" index="0" allow="rail" speed="13.89" length="100.00" shape="100.00,0.00 2.16,0.00"/>
    </edge>
    <edge id="-E2" from="J3" to="J2" priority="-1" spreadType="center" bidi="E2">
        <lane id="-E2_0" index="0" allow="rail" speed="13.89" length="100.00" shape="194.64,0.00 100.00,0.00"/>
    </edge>
    <edge id="-E3" from="J4" to="J3" priority="-1" spreadType="center" bidi="E3">
        <lane id="-E3_0" index="0" allow="rail" speed="13.89" length="100.00" shape="300.00,0.00 202.16,0.00"/>
    </edge>
    <edge id="-E4" from="J5" to="J4" priority="-1" spreadType="center" bidi="E4">
        <lane id="-E4_0" index="0" allow="rail" speed="13.89" length="100.00" shape="400.00,0.00 300.00,0.00"/>
    </edge>
    <edge id="-E5" from="J1" to="J6" priority="-1" spreadType="center" bidi="E5">
        <lane id="-E5_0" index="0" allow="rail" speed="13.89" length="141.42" shape="-3.79,3.79 -100.00,100.00"/>
    </edge>
    <edge id="-E6" from="J3" to="J7" priority="-1" spreadType="center" bidi="E6">
        <lane id="-E6_0" index="0" allow="rail" speed="13.89" length="141.42" shape="196.21,3.79 100.00,100.00"/>
    </edge>
    <edge id="-E7" from="J8" to="J5" priority="-1" spreadType="center" bidi="E7">
        <lane id="-E7_0" index="0" allow="rail" speed="13.89" length="100.00" shape="500.00,0.00 400.00,0.00"/>
    </edge>
    <edge id="E0" from="J0" to="J1" priority="-1" spreadType="center" bidi="-E0">
        <lane id="E0_0" index="0" allow="rail" speed="13.89" length="100.00" shape="-100.00,0.00 -5.36,0.00"/>
    </edge>
    <edge id="E1" from="J1" to="J2" priority="-1" spreadType="center" bidi="-E1">
        <lane id="E1_0" index="0" allow="rail" speed="13.89" length="100.00" shape="2.16,0.00 100.00,0.00"/>
    </edge>
    <edge id="E2" from="J2" to="J3" priority="-1" spreadType="center" bidi="-E2">
        <lane id="E2_0" index="0" allow="rail" speed="13.89" length="100.00" shape="100.00,0.00 194.64,0.00"/>
    </edge>
    <edge id="E3" from="J3" to="J4" priority="-1" spreadType="center" bidi="-E3">
        <lane id="E3_0" index="0" allow="rail" speed="13.89" length="100.00" shape="202.16,0.00 300.00,0.00"/>
    </edge>
    <edge id="E4" from="J4" to="J5" priority="-1" spreadType="center" bidi="-E4">
        <lane id="E4_0" index="0" allow="rail" speed="13.89" length="100.00" shape="300.00,0.00 400.00,0.00"/>
    </edge>
    <edge id="E5" from="J6" to="J1" priority="-1" spreadType="center" bidi="-E5">
        <lane id="E5_0" index="0" allow="rail" speed="13.89" length="141.42" shape="-100.00,100.00 -3.79,3.79"/>
    </edge>
    <edge id="E6" from="J7" to="J3" priority="-1" spreadType="center" bidi="-E6">
        <lane id="E6_0" index="0" allow="rail" speed="13.89" length="141.42" shape="100.00,100.00 196.21,3.79"/>
    </edge>
    <edge id="E7" from="J5" to="J8" priority="-1" spreadType="center" bidi="-E7">
        <lane id="E7_0" index="0" allow="rail" speed="13.89" length="100.00" shape="400.00,0.00 500.00,0.00"/>
    </edge>

    <junction id="J0" type="dead_end" x="-100.00" y="0.00" incLanes="-E0_0" intLanes="" shape="-100.00,1.60 -100.00,-1.60 -100.00,1.60 -100.00,-1.60"/>
    <junction id="J1" type="priority" x="0.00" y="0.00" incLanes="-E1_0 E0_0 E5_0" intLanes="" shape="2.16,1.60 2.16,-1.60 -5.36,-1.60 -5.36,1.60 -4.65,1.72 -4.50,1.87 -4.50,2.07 -4.64,2.34 -4.92,2.66 -2.66,4.92 -0.65,3.08 0.21,2.43 0.96,1.97 1.61,1.69">
        <request index="0" response="0000" foes="0000"/>
        <request index="1" response="0000" foes="1000"/>
        <request index="2" response="0000" foes="1000"/>
        <request index="3" response="0110" foes="0110"/>
    </junction>
    <junction id="J2" type="rail_signal" x="100.00" y="0.00" incLanes="-E2_0 E1_0" intLanes="" shape="100.00,1.60 100.00,-1.60 100.00,1.60">
        <request index="0" response="00" foes="00"/>
        <request index="1" response="00" foes="00"/>
    </junction>
    <junction id="J3" type="priority" x="200.00" y="0.00" incLanes="-E3_0 E2_0 E6_0" intLanes="" shape="202.16,1.60 202.16,-1.60 194.64,-1.60 194.64,1.60 195.35,1.72 195.50,1.87 195.50,2.07 195.36,2.34 195.08,2.66 197.34,4.92 198.86,3.14 199.43,2.49 200.07,2.00 200.93,1.70">
        <request index="0" response="0000" foes="0000"/>
        <request index="1" response="0000" foes="1000"/>
        <request index="2" response="0000" foes="1000"/>
        <request index="3" response="0110" foes="0110"/>
    </junction>
    <junction id="J4" type="rail_signal" x="300.00" y="0.00" incLanes="-E4_0 E3_0" intLanes="" shape="300.00,1.60 300.00,-1.60 300.00,1.60">
        <request index="0" response="00" foes="00"/>
        <request index="1" response="00" foes="00"/>
    </junction>
    <junction id="J5" type="rail_signal" x="400.00" y="0.00" incLanes="-E7_0 E4_0" intLanes="" shape="400.00,1.60 400.00,-1.60 400.00,1.60">
        <request index="0" response="00" foes="00"/>
        <request index="1" response="00" foes="00"/>
    </junction>
    <junction id="J6" type="dead_end" x="-100.00" y="100.00" incLanes="-E5_0" intLanes="" shape="-98.87,101.13 -101.13,98.87 -98.87,101.13 -101.13,98.87"/>
    <junction id="J7" type="dead_end" x="100.00" y="100.00" incLanes="-E6_0" intLanes="" shape="101.13,101.13 98.87,98.87 101.13,101.13 98.87,98.87"/>
    <junction id="J8" type="dead_end" x="500.00" y="0.00" incLanes="E7_0" intLanes="" shape="500.00,-1.60 500.00,1.60 500.00,-1.60 500.00,1.60"/>

    <connection from="-E1" to="-E5" fromLane="0" toLane="0" dir="r" state="M"/>
    <connection from="-E1" to="-E0" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from="-E2" to="-E1" fromLane="0" toLane="0" uncontrolled="1" dir="s" state="M"/>
    <connection from="-E3" to="-E6" fromLane="0" toLane="0" dir="r" state="M"/>
    <connection from="-E3" to="-E2" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from="-E4" to="-E3" fromLane="0" toLane="0" tl="J4" linkIndex="0" dir="s" state="O"/>
    <connection from="-E7" to="-E4" fromLane="0" toLane="0" tl="J5" linkIndex="0" dir="s" state="o"/>
    <connection from="E0" to="E1" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from="E1" to="E2" fromLane="0" toLane="0" tl="J2" linkIndex="0" dir="s" state="O"/>
    <connection from="E2" to="E3" fromLane="0" toLane="0" dir="s" state="M"/>
    <connection from="E3" to="E4" fromLane="0" toLane="0" uncontrolled="1" dir="s" state="M"/>
    <connection from="E4" to="E7" fromLane="0" toLane="0" uncontrolled="1" dir="s" state="M"/>
    <connection from="E5" to="E1" fromLane="0" toLane="0" dir="l" state="M"/>
    <connection from="E6" to="E3" fromLane="0" toLane="0" dir="l" state="M"/>

</net>

=== eclipse-sumo/sumo/sumo/tests/sumo/cf_model/jam_resolution/bottleneck_confluence/net.net.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on Thu 04 Oct 2012 03:49:47 PM CEST by Netedit Version dev-SVN-r12771
<?xml version="1.0" encoding="UTF-8"?>

<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo-sim.org/xsd/netedit.exeConfiguration.xsd">

    <input>
        <sumo-net-file value="/home/erdm_ja/debug/bottleneck_capacity/net.net.xml"/>
    </input>

    <output>
        <output-file value="/home/erdm_ja/debug/bottleneck_capacity/net.net.xml"/>
    </output>

    <processing>
        <no-internal-links value="true"/>
        <no-turnarounds value="true"/>
        <offset.disable-normalization value="true"/>
    </processing>

</configuration>
-->

<net version="0.13" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo-sim.org/xsd/net_file.xsd">

    <location netOffset="0.00,0.00" convBoundary="-500.00,-100.00,500.00,100.00" origBoundary="-10000000000.00,-10000000000.00,10000000000.00,10000000000.00" projParameter="!"/>

    <edge id="in1" from="gneJ0" to="gneJ1" priority="1">
        <lane id="in1_0" index="0" speed="13.89" length="492.81" shape="-500.97,95.15 -17.73,-1.50"/>
        <lane id="in1_1" index="1" speed="13.89" length="492.81" shape="-500.32,98.38 -17.08,1.73"/>
    </edge>
    <edge id="in2" from="gneJ2" to="gneJ1" priority="1">
        <lane id="in2_0" index="0" speed="13.89" length="491.49" shape="-499.03,-104.85 -17.08,-8.46"/>
        <lane id="in2_1" index="1" speed="13.89" length="491.49" shape="-499.68,-101.62 -17.73,-5.23"/>
    </edge>
    <edge id="out" from="gneJ1" to="gneJ3" priority="1">
        <lane id="out_0" index="0" speed="13.89" length="498.50" shape="1.50,-1.65 500.00,-1.65"/>
    </edge>

    <junction id="gneJ0" type="unregulated" x="-500.00" y="100.00" incLanes="" intLanes="" shape="-500.01,99.95 -501.28,93.58">
    </junction>
    <junction id="gneJ1" type="priority" x="0.00" y="0.00" incLanes="in2_0 in2_1 in1_0 in1_1" intLanes="" shape="1.50,-0.05 1.50,-3.25 -16.77,-10.03 -18.04,-3.66 -18.04,-3.07 -16.77,3.30">
        <request index="0" response="00" foes="10"/>
        <request index="1" response="01" foes="01"/>
    </junction>
    <junction id="gneJ2" type="unregulated" x="-500.00" y="-100.00" incLanes="" intLanes="" shape="-499.99,-100.05 -498.72,-106.42">
    </junction>
    <junction id="gneJ3" type="unregulated" x="500.00" y="0.00" incLanes="out_0" intLanes="" shape="500.00,-3.25 500.00,-0.05">
    </junction>

    <connection from="in1" to="out" fromLane="0" toLane="0" dir="s" state="m"/>
    <connection from="in2" to="out" fromLane="0" toLane="0" dir="s" state="M"/>

</net>
