=== eclipse-sumo/sumo/data/xsd/nodes_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:include schemaLocation="types/base.xsd" />

    <xsd:element name="nodes" type="nodesType">
        <xsd:key name="nodeKey">
            <xsd:selector xpath="node"/>
            <xsd:field xpath="@id"/>
        </xsd:key>
    </xsd:element>

    <xsd:complexType name="nodesType">
        <xsd:sequence>
            <xsd:element name="location" type="locationType" minOccurs="0" maxOccurs="1"/>
            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                <xsd:element name="node" type="nodeType"/>
                <xsd:element name="delete" type="deleteType"/>
                <xsd:element name="join" type="joinType"/>
                <xsd:element name="joinExclude" type="joinExcludeType"/>
            </xsd:choice>
        </xsd:sequence>
        <xsd:attribute name="version" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:pattern value="\d+.\d+"></xsd:pattern>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="nodeTypeWithoutID">
        <xsd:sequence>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="x" type="floatType" use="optional"/>
        <xsd:attribute name="y" type="floatType" use="optional"/>
        <xsd:attribute name="z" type="floatType" use="optional"/>
        <xsd:attribute name="type" type="nodeTypeType" use="optional"/>
        <xsd:attribute name="tl" type="xsd:string" use="optional"/>
        <xsd:attribute name="tlType" type="tlTypeType" use="optional"/>
        <xsd:attribute name="tlLayout" type="tlLayoutType" use="optional"/>
        <xsd:attribute name="controlledInner" type="xsd:string" use="optional"/>
        <xsd:attribute name="shape" type="shapeType" use="optional"/>
        <xsd:attribute name="name" type="xsd:string" use="optional"/>
        <xsd:attribute name="radius" type="nonNegativeFloatTypeWithErrorValue" use="optional"/>
        <xsd:attribute name="keepClear" type="boolType" use="optional"/>
        <xsd:attribute name="rightOfWay" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="default"/>
                    <xsd:enumeration value="mixedPriority"/>
                    <xsd:enumeration value="allwayStop"/>
                    <xsd:enumeration value="edgePriority"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="fringe" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="default"/>
                    <xsd:enumeration value="outer"/>
                    <xsd:enumeration value="inner"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="roundabout" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="1"/>
                    <xsd:enumeration value="0"/>
                    <xsd:enumeration value="default"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="nodeType">
        <xsd:complexContent>
            <xsd:extension base="nodeTypeWithoutID">
                <xsd:attribute name="id" type="idType" use="required"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="deleteType">
        <xsd:attribute name="id" type="idType" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="joinType">
        <xsd:complexContent>
            <xsd:extension base="nodeTypeWithoutID">
                <xsd:attribute name="nodes" type="xsd:string" use="required"/>
                <xsd:attribute name="id" type="idType" use="optional"/>
                <xsd:attribute name="reset" type="boolType" use="optional"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="joinExcludeType">
        <xsd:attribute name="nodes" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:simpleType name="tlLayoutType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="opposites"/>
            <xsd:enumeration value="incoming"/>
            <xsd:enumeration value="alternateOneWay"/>
        </xsd:restriction>
    </xsd:simpleType>

</xsd:schema>

=== eclipse-sumo/sumo/tests/netconvert/bugs/ticket13581/input_plain.nod.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2023-07-07 09:09:30 by Eclipse SUMO netedit Version v1_18_0+0172-1b2313e
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/neteditConfiguration.xsd">

    <input>
        <sumo-net-file value="nottinghill-1.net.xml"/>
    </input>

    <processing>
        <geometry.min-radius.fix.railways value="false"/>
        <geometry.max-grade.fix value="false"/>
        <offset.disable-normalization value="true"/>
        <lefthand value="1"/>
    </processing>

    <building_defaults>
        <default.spreadtype value="roadCenter"/>
    </building_defaults>

    <tls_building>
        <tls.ignore-internal-junction-jam value="1"/>
    </tls_building>

    <junctions>
        <no-internal-links value="true"/>
        <no-turnarounds value="true"/>
        <junctions.corner-detail value="5"/>
        <junctions.limit-turn-speed value="5.50"/>
        <rectangular-lane-cut value="0"/>
    </junctions>

    <pedestrian>
        <walkingareas value="0"/>
    </pedestrian>

</configuration>
-->

<nodes version="1.16" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/nodes_file.xsd">
    <location netOffset="-694502.26,-5710053.81" convBoundary="13.58,33.23,171.24,150.70" origBoundary="-0.200593,51.507755,-0.142249,51.515288" projParameter="+proj=utm +zone=30 +ellps=WGS84 +datum=WGS84 +units=m +no_defs"/>

    <node id="102091" x="129.51" y="141.38" type="priority"/>
    <node id="10597779676" x="120.63" y="115.85" type="traffic_light" tl="10597779676">
        <param key="highway" value="traffic_signals"/>
        <param key="traffic_signals:direction" value="forward"/>
    </node>
    <node id="1937948454" x="13.58" y="92.78" type="dead_end" fringe="outer">
        <param key="highway" value="traffic_signals"/>
        <param key="traffic_signals:direction" value="forward"/>
    </node>
    <node id="2314766396" x="128.02" y="130.92" type="traffic_light" tl="GS_2314766396"/>
    <node id="25579302" x="49.97" y="115.15" type="dead_end"/>
    <node id="7123959642" x="171.24" y="150.70" type="dead_end"/>
    <node id="7208284743" x="109.60" y="134.93" type="traffic_light" tl="7208284743">
        <param key="highway" value="traffic_signals"/>
        <param key="traffic_signals:direction" value="forward"/>
    </node>
    <node id="841514178" x="145.57" y="142.09" type="right_before_left"/>
    <node id="841519716" x="128.69" y="101.35" type="priority"/>
    <node id="841519718" x="118.22" y="137.48" type="traffic_light" tl="841519718">
        <param key="button_operated" value="yes"/>
        <param key="crossing" value="traffic_signals"/>
        <param key="crossing_ref" value="pelican"/>
        <param key="highway" value="crossing"/>
        <param key="tactile_paving" value="yes"/>
        <param key="traffic_signals:vibration" value="yes"/>
    </node>
    <node id="841519720" x="144.29" y="139.79" type="priority">
        <param key="highway" value="traffic_signals"/>
        <param key="traffic_signals:direction" value="forward"/>
    </node>
    <node id="841519722" x="121.30" y="128.20" type="priority">
        <param key="crossing" value="traffic_signals"/>
        <param key="crossing_ref" value="pelican"/>
        <param key="highway" value="crossing"/>
    </node>
    <node id="841519723" x="112.79" y="124.82" type="traffic_light" tl="GS_841519723"/>
    <node id="841519724" x="128.37" y="122.02" type="priority">
        <param key="crossing" value="traffic_signals"/>
        <param key="crossing_ref" value="pelican"/>
        <param key="highway" value="crossing"/>
    </node>
    <node id="841519725" x="119.03" y="118.74" type="priority">
        <param key="crossing" value="traffic_signals"/>
        <param key="crossing_ref" value="pelican"/>
        <param key="highway" value="crossing"/>
    </node>
    <node id="841529961" x="144.62" y="33.23" type="dead_end"/>
</nodes>

=== eclipse-sumo/sumo/tests/netedit/processing/ticket2327/net.nod.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2024-08-08 13:02:39 by Eclipse SUMO netedit Version v1_20_0+1763-a87dd661c22
<neteditConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/neteditConfiguration.xsd">

    <input>
        <sumo-net-file value="D:\Netedit_dev\tests\netedit\processing\ticket2327\net.net.xml"/>
    </input>

    <processing>
        <geometry.min-radius.fix.railways value="false"/>
        <geometry.max-grade.fix value="false"/>
        <offset.disable-normalization value="true"/>
        <lefthand value="0"/>
    </processing>

    <junctions>
        <no-internal-links value="false"/>
        <no-turnarounds value="true"/>
        <junctions.corner-detail value="5"/>
        <junctions.limit-turn-speed value="5.50"/>
        <rectangular-lane-cut value="0"/>
    </junctions>

    <pedestrian>
        <walkingareas value="0"/>
    </pedestrian>

</neteditConfiguration>
-->

<nodes version="1.20" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/nodes_file.xsd">
    <location netOffset="0.00,0.00" convBoundary="-60.00,-30.00,60.00,30.00" origBoundary="-10000000000.000000,-10000000000.000000,10000000000.000000,10000000000.000000" projParameter="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"/>

    <node id="J0" x="0.00" y="20.00" type="priority"/>
    <node id="J1" x="30.00" y="0.00" type="priority"/>
    <node id="J2" x="0.00" y="-20.00" type="priority"/>
    <node id="Junction0" x="-30.00" y="-20.00" type="priority"/>
    <node id="Junction1" x="30.00" y="-20.00" type="priority"/>
    <node id="Junction2" x="30.00" y="20.00" type="priority"/>
    <node id="Junction3" x="-30.00" y="20.00" type="priority"/>
    <node id="Junction4" x="-30.00" y="0.00" type="priority"/>
    <node id="Junction5" x="0.00" y="0.00" type="priority"/>
    <node id="JunctionExtern0" x="-60.00" y="0.00" type="priority"/>
    <node id="JunctionExtern1" x="60.00" y="0.00" type="priority"/>
</nodes>

=== eclipse-sumo/sumo/tests/netedit/network/junctions/inspect/no_tls/net.nod.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2024-06-28 11:41:54 by Eclipse SUMO netedit Version v1_20_0+0903-50ed8d6b852
This data file and the accompanying materials
are made available under the terms of the Eclipse Public License v2.0
which accompanies this distribution, and is available at
http://www.eclipse.org/legal/epl-v20.html
This file may also be made available under the following Secondary
Licenses when the conditions for such availability set forth in the Eclipse
Public License 2.0 are satisfied: GNU General Public License, version 2
or later which is available at
https://www.gnu.org/licenses/old-licenses/gpl-2.0-standalone.html
SPDX-License-Identifier: EPL-2.0 OR GPL-2.0-or-later
<neteditConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/neteditConfiguration.xsd">

    <input>
        <additional-files value="C:\Users\alva_pa\.texttest\tmp\netedit.gui.28Jun114019.6628\netedit.gui\network\junctions\inspect\id\additionals.add.xml"/>
        <route-files value="C:\Users\alva_pa\.texttest\tmp\netedit.gui.28Jun114019.6628\netedit.gui\network\junctions\inspect\id\routes.rou.xml"/>
        <data-files value="C:\Users\alva_pa\.texttest\tmp\netedit.gui.28Jun114019.6628\netedit.gui\network\junctions\inspect\id\datas.dat.xml"/>
        <sumo-net-file value="D:\Netedit_dev\tests\netedit\network\junctions\inspect\net.net.xml"/>
    </input>

    <output>
        <write-license value="true"/>
    </output>

    <processing>
        <geometry.min-radius.fix.railways value="false"/>
        <geometry.max-grade.fix value="false"/>
        <offset.disable-normalization value="true"/>
        <lefthand value="0"/>
    </processing>

    <junctions>
        <no-turnarounds value="true"/>
        <junctions.corner-detail value="5"/>
        <junctions.limit-turn-speed value="5.50"/>
        <rectangular-lane-cut value="0"/>
    </junctions>

    <pedestrian>
        <walkingareas value="0"/>
    </pedestrian>

    <netedit>
        <ignore-supermode-question value="true"/>
    </netedit>

    <visualisation>
        <gui-settings-file value="C:\Users\alva_pa\.texttest\tmp\netedit.gui.28Jun114019.6628\netedit.gui\network\junctions\inspect\id\gui-settings.xml"/>
        <window-size value="1280, 720"/>
        <window-pos value="50,50"/>
        <gui-testing value="true"/>
        <gui-testing.setting-output value="C:\Users\alva_pa\.texttest\tmp\netedit.gui.28Jun114019.6628\netedit.gui\network\junctions\inspect\id\guisettingsoutput.xml"/>
    </visualisation>

    <report>
        <no-warnings value="true"/>
        <error-log value="C:\Users\alva_pa\.texttest\tmp\netedit.gui.28Jun114019.6628\netedit.gui\network\junctions\inspect\id\log.txt"/>
    </report>

</neteditConfiguration>
-->

<nodes version="1.20" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/nodes_file.xsd">
    <location netOffset="0.00,0.00" convBoundary="-60.00,-30.00,60.00,30.00" origBoundary="-10000000000.000000,-10000000000.000000,10000000000.000000,10000000000.000000" projParameter="+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs"/>

    <node id="JunctionBot" x="0.00" y="-25.00" type="dead_end"/>
    <node id="JunctionCenter" x="0.00" y="0.00" type="priority"/>
    <node id="JunctionExtern0" x="-60.00" y="0.00" type="priority"/>
    <node id="JunctionExtern1" x="60.00" y="0.00" type="priority"/>
    <node id="JunctionLeft" x="-25.00" y="0.00" type="dead_end"/>
    <node id="JunctionRight" x="25.00" y="0.00" type="dead_end"/>
    <node id="JunctionTop" x="0.00" y="25.00" type="dead_end"/>
</nodes>
