=== eclipse-sumo/sumo/data/xsd/statistic_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xsd:include schemaLocation="baseTypes.xsd"/>

    <xsd:element name="statistics">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="performance">
                    <xsd:complexType>
                        <xsd:attribute name="clockBegin" use="required" type="timeType"/>
                        <xsd:attribute name="clockEnd" use="required" type="timeType"/>
                        <xsd:attribute name="clockDuration" use="required" type="timeType"/>
                        <xsd:attribute name="traciDuration" use="required" type="timeType"/>
                        <xsd:attribute name="realTimeFactor" use="required" type="nonNegativeFloatTypeWithErrorValue"/>
                        <xsd:attribute name="vehicleUpdatesPerSecond" use="required" type="nonNegativeFloatTypeWithErrorValue"/>
                        <xsd:attribute name="personUpdatesPerSecond" use="required" type="nonNegativeFloatTypeWithErrorValue"/>
                        <xsd:attribute name="begin" use="required" type="timeType"/>
                        <xsd:attribute name="end" use="required" type="timeType"/>
                        <xsd:attribute name="duration" use="required" type="timeType"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="vehicles">
                    <xsd:complexType>
                        <xsd:attribute name="loaded" use="required" type="xsd:nonNegativeInteger"/>
                        <xsd:attribute name="inserted" use="required" type="xsd:nonNegativeInteger"/>
                        <xsd:attribute name="running" use="required" type="xsd:nonNegativeInteger"/>
                        <xsd:attribute name="waiting" use="required" type="xsd:nonNegativeInteger"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="teleports">
                    <xsd:complexType>
                        <xsd:attribute name="total" use="required" type="xsd:nonNegativeInteger"/>
                        <xsd:attribute name="jam" use="required" type="xsd:nonNegativeInteger"/>
                        <xsd:attribute name="yield" use="required" type="xsd:nonNegativeInteger"/>
                        <xsd:attribute name="wrongLane" use="required" type="xsd:nonNegativeInteger"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="safety">
                    <xsd:complexType>
                        <xsd:attribute name="collisions" use="required" type="xsd:nonNegativeInteger"/>
                        <xsd:attribute name="emergencyStops" use="required" type="xsd:nonNegativeInteger"/>
                        <xsd:attribute name="emergencyBraking" use="required" type="xsd:nonNegativeInteger"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="persons">
                    <xsd:complexType>
                        <xsd:attribute name="loaded" use="required" type="xsd:nonNegativeInteger"/>
                        <xsd:attribute name="running" use="required" type="xsd:nonNegativeInteger"/>
                        <xsd:attribute name="jammed" use="required" type="xsd:nonNegativeInteger"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="personTeleports">
                    <xsd:complexType>
                        <xsd:attribute name="total" use="required" type="xsd:nonNegativeInteger"/>
                        <xsd:attribute name="abortWait" use="required" type="xsd:nonNegativeInteger"/>
                        <xsd:attribute name="wrongDest" use="required" type="xsd:nonNegativeInteger"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="vehicleTripStatistics" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:attribute name="count" use="required" type="xsd:nonNegativeInteger"/>
                        <xsd:attribute name="routeLength" use="required" type="nonNegativeFloatType"/>
                        <xsd:attribute name="speed" use="required" type="nonNegativeFloatType"/>
                        <xsd:attribute name="duration" use="required" type="timeType"/>
                        <xsd:attribute name="waitingTime" use="required" type="timeType"/>
                        <xsd:attribute name="timeLoss" use="required" type="timeType"/>
                        <xsd:attribute name="departDelay" use="required" type="timeType"/>
                        <xsd:attribute name="departDelayWaiting" use="required" type="timeTypeWithErrorValue"/>
                        <xsd:attribute name="totalTravelTime" use="required" type="timeType"/>
                        <xsd:attribute name="totalDepartDelay" use="required" type="timeType"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="bikeTripStatistics" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:attribute name="count" use="required" type="xsd:nonNegativeInteger"/>
                        <xsd:attribute name="routeLength" use="required" type="nonNegativeFloatType"/>
                        <xsd:attribute name="speed" use="required" type="nonNegativeFloatType"/>
                        <xsd:attribute name="duration" use="required" type="timeType"/>
                        <xsd:attribute name="waitingTime" use="required" type="timeType"/>
                        <xsd:attribute name="timeLoss" use="required" type="timeType"/>
                        <xsd:attribute name="totalTravelTime" use="required" type="timeType"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="pedestrianStatistics" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:attribute name="number" use="required" type="xsd:nonNegativeInteger"/>
                        <xsd:attribute name="routeLength" use="required" type="nonNegativeFloatType"/>
                        <xsd:attribute name="duration" use="required" type="timeType"/>
                        <xsd:attribute name="timeLoss" use="required" type="timeType"/>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="rideStatistics" minOccurs="0" maxOccurs="1" type="rideStatisticsType"/>
                <xsd:element name="transportStatistics" minOccurs="0" maxOccurs="1" type="rideStatisticsType"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="rideStatisticsType">
		<xsd:attribute name="number" use="required" type="xsd:nonNegativeInteger"/>
		<xsd:attribute name="routeLength" use="optional" type="nonNegativeFloatType"/>
		<xsd:attribute name="duration" use="optional" type="timeType"/>
		<xsd:attribute name="bus" use="optional" type="xsd:nonNegativeInteger"/>
		<xsd:attribute name="train" use="optional" type="xsd:nonNegativeInteger"/>
		<xsd:attribute name="taxi" use="optional" type="xsd:nonNegativeInteger"/>
		<xsd:attribute name="bike" use="optional" type="xsd:nonNegativeInteger"/>
		<xsd:attribute name="aborted" use="optional" type="xsd:nonNegativeInteger"/>
    </xsd:complexType>

</xsd:schema>

=== eclipse-sumo/sumo/tests/tools/visualization/plotXMLAttributes/stats_joined/input_data2.xml
<?xml version="1.0" encoding="UTF-8"?>
<statistics xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/statistic_file.xsd">
    <performance clockBegin="401193.99" clockEnd="401214.80" clockDuration="20.81" traciDuration="48.33" realTimeFactor="1459.36" vehicleUpdatesPerSecond="16670.03" personUpdatesPerSecond="705860.08" begin="0.00" end="30362.00" duration="30362.00"/>
    <vehicles loaded="1004" inserted="1004" running="0" waiting="0"/>
    <teleports total="2" jam="0" yield="0" wrongLane="0"/>
    <safety collisions="2" emergencyStops="0"/>
    <persons loaded="502" running="0" jammed="0"/>
    <personTeleports total="0" abortWait="0" wrongDest="0"/>
    <vehicleTripStatistics count="0" routeLength="0.00" speed="0.00" duration="0.00" waitingTime="0.00" timeLoss="0.00" departDelay="0.00" departDelayWaiting="-1.00" totalTravelTime="0.00" totalDepartDelay="330446.00"/>
    <bikeTripStatistics count="1004" routeLength="1151.26" speed="3.57" duration="345.44" waitingTime="68.87" timeLoss="130.66" totalTravelTime="346820.00"/>
    <pedestrianStatistics number="0" routeLength="0.00" duration="0.00" timeLoss="0.00"/>
    <rideStatistics number="1004" waitingTime="329.13" routeLength="1151.26" duration="345.44" bus="0" train="0" taxi="0" bike="1004" aborted="0"/>
    <transportStatistics number="0"/>
</statistics>
