=== eclipse-sumo/sumo/sumo/docs/internet/xsd/additional_file.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:include schemaLocation="routeTypes.xsd" />
    <xsd:include schemaLocation="meandataTypes.xsd"/>

    <xsd:element name="additional" type="additionalType"/>
    
    <xsd:complexType name="additionalType">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="vTypeProbe" type="vTypeProbeType" minOccurs="0"/>
            <xsd:element name="e1Detector" type="e1DetectorType" minOccurs="0"/>
            <xsd:element name="inductionLoop" type="e1DetectorType" minOccurs="0"/>
            <xsd:element name="e2Detector" type="e2DetectorType" minOccurs="0"/>
            <xsd:element name="laneAreaDetector" type="e2DetectorType" minOccurs="0"/>
            <xsd:element name="e3Detector" type="e3DetectorType" minOccurs="0"/>
            <xsd:element name="entryExitDetector" type="e3DetectorType" minOccurs="0"/>
            <xsd:element name="edgeData" type="meandataType" minOccurs="0"/>
            <xsd:element name="laneData" type="meandataType" minOccurs="0"/>
            <xsd:element name="timedEvent" type="timedEventType" minOccurs="0"/>
            <xsd:element name="tlLogic" type="tlLogicType" minOccurs="0"/>
            <xsd:element name="WAUT" type="WAUTType" minOccurs="0"/>
            <xsd:element name="wautJunction" type="wautJunctionType" minOccurs="0"/>
            <xsd:element name="variableSpeedSign" type="variableSpeedSignType" minOccurs="0"/>
            <xsd:element name="routeProbe" type="routeProbeType" minOccurs="0"/>
            <xsd:element name="rerouter" type="rerouterType" minOccurs="0"/>
            <xsd:element name="instantInductionLoop" type="instantInductionLoopType" minOccurs="0"/>
            <xsd:element name="busStop" type="busStopType" minOccurs="0"/>
            <xsd:element name="calibrator" type="calibratorType" minOccurs="0"/>
            <xsd:element name="vaporizer" type="vaporizerType" minOccurs="0"/>

            <xsd:element name="vTypeDistribution" type="vTypeDistributionType" minOccurs="0"/>
            <xsd:element name="routeDistribution" type="routeDistributionType" minOccurs="0"/>
            <xsd:element name="vType" type="vTypeType" minOccurs="0"/>
            <xsd:element name="route" type="routeType" minOccurs="0"/>
            <xsd:element name="vehicle" type="vehicleType" minOccurs="0"/>
            <xsd:element name="flow" type="flowType" minOccurs="0"/>
            <xsd:element name="person" type="personType" minOccurs="0"/>

            <xsd:element name="interval" type="intervalType" minOccurs="0"/>

            <xsd:element name="polygon" type="polygonType" minOccurs="0"/>
            <xsd:element name="poi" type="poiType" minOccurs="0"/>

            <xsd:element name="include" minOccurs="0">
                <xsd:complexType>
                    <xsd:attribute name="href" type="xsd:string"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:choice>

    </xsd:complexType>
    
    <xsd:complexType name="e1DetectorType">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="lane" type="xsd:string" use="required"/>
        <xsd:attribute name="pos" type="xsd:float" use="required"/>
        <xsd:attribute name="freq" type="positiveFloatType" use="required"/>
        <xsd:attribute name="file" type="xsd:string" use="required"/>
        <xsd:attribute name="splitByType" use="optional" type="boolType"/>
        <xsd:attribute name="friendlyPos" use="optional" type="boolType"/>
    </xsd:complexType>

    <xsd:complexType name="vTypeProbeType">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="freq" type="positiveFloatType" use="required"/>
        <xsd:attribute name="file" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="e2DetectorType">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="lane" type="xsd:string" use="required"/>
        <xsd:attribute name="pos" type="xsd:float" use="required"/>
        <xsd:attribute name="file" type="xsd:string" use="required"/>
        <xsd:attribute name="length" type="xsd:float" use="required"/>
        <xsd:attribute name="freq" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="tl" type="xsd:string" use="optional"/>
        <xsd:attribute name="to" type="xsd:string" use="optional"/>
        <xsd:attribute name="cont" type="boolType" use="optional"/>
        <xsd:attribute name="timeThreshold" type="xsd:int" use="optional"/>
        <xsd:attribute name="speedThreshold" type="xsd:float" use="optional"/>
        <xsd:attribute name="jamThreshold" type="xsd:float" use="optional"/>
        <xsd:attribute name="friendlyPos" use="optional" type="boolType"/>
    </xsd:complexType>

    <xsd:complexType name="e3DetectorType">
        <xsd:sequence>
            <xsd:element name="detEntry" type="detEntryExitType"
                minOccurs="1" maxOccurs="unbounded"/>
            <xsd:element name="detExit" type="detEntryExitType"
                minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="freq" type="positiveFloatType" use="required"/>
        <xsd:attribute name="file" type="xsd:string" use="required"/>
        <xsd:attribute name="timeThreshold" type="xsd:float" use="optional"/>
        <xsd:attribute name="speedThreshold" type="nonNegativeFloatType" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="detEntryExitType">
        <xsd:attribute name="lane" type="xsd:string" use="required"/>
        <xsd:attribute name="pos" type="xsd:float" use="required"/>
        <xsd:attribute name="friendlyPos" use="optional" type="boolType">
        </xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="meandataType">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="type" use="optional">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="emissions"/>
		    <xsd:enumeration value="hbefa"/> <!-- deprecated in favor of emissions -->
                    <xsd:enumeration value="harmonoise"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="freq" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="file" type="xsd:string" use="required"/>
        <xsd:attribute name="begin" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="end" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="maxTraveltime" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="excludeEmpty" use="optional">
            <xsd:simpleType>
                <xsd:union memberTypes="boolType">
                    <xsd:simpleType>
                        <xsd:restriction base="xsd:string">
                            <xsd:enumeration value="defaults"/>
                        </xsd:restriction>
                    </xsd:simpleType> 
                </xsd:union>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="withInternal" type="boolType" use="optional"/>
        <xsd:attribute name="trackVehicles" type="boolType" use="optional"/>
        <xsd:attribute name="vTypes" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="timedEventType">
        <xsd:attribute name="type" use="required">
            <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                    <xsd:enumeration value="SaveTLSStates"/>
                    <xsd:enumeration value="SaveTLSSwitchTimes"/>
                    <xsd:enumeration value="SaveTLSSwitchStates"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        <xsd:attribute name="source" type="xsd:string" use="required"/>
        <xsd:attribute name="dest" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="WAUTType">
        <xsd:sequence>
            <xsd:element name="wautSwitch" type="wautSwitchType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="refTime" type="xsd:int" use="required"/>
        <xsd:attribute name="startProg" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="wautSwitchType">
        <xsd:attribute name="time" type="xsd:int" use="required"/>
        <xsd:attribute name="to" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="wautJunctionType">
        <xsd:attribute name="wautID" type="xsd:string" use="required"/>
        <xsd:attribute name="junctionID" type="xsd:string" use="required"/>
        <xsd:attribute name="procedure" type="xsd:string"/>
        <xsd:attribute name="synchron" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="variableSpeedSignType">
        <xsd:sequence minOccurs="0">
            <xsd:element name="step" minOccurs="1" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:attribute name="time" type="nonNegativeFloatType" use="required"/>
                    <xsd:attribute name="speed" type="xsd:float" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="lanes" type="xsd:string" use="required"/>
        <xsd:attribute name="file" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="routeProbeType">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="edge" type="xsd:string" use="optional"/>
        <xsd:attribute name="begin" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="freq" type="positiveFloatType" use="required"/>
        <xsd:attribute name="file" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="rerouterType">
        <xsd:sequence minOccurs="0">
            <xsd:element name="interval" minOccurs="1" maxOccurs="unbounded">
                <xsd:complexType>
                    <xsd:choice maxOccurs="unbounded">
                        <xsd:element name="closingReroute">
                            <xsd:complexType>
                                <xsd:attribute name="id" type="xsd:string" use="required"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name="destProbReroute">
                            <xsd:complexType>
                                <xsd:attribute name="id" type="xsd:string" use="required"/>
                                <xsd:attribute name="probability" type="positiveFloatType"/>
                            </xsd:complexType>
                        </xsd:element>
                        <xsd:element name="routeProbReroute">
                            <xsd:complexType>
                                <xsd:attribute name="id" type="xsd:string" use="required"/>
                                <xsd:attribute name="probability" type="positiveFloatType"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:choice>
                    <xsd:attribute name="begin" type="nonNegativeFloatType" use="required"/>
                    <xsd:attribute name="end" type="nonNegativeFloatType" use="required"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="edges" type="xsd:string" use="optional"/>
        <xsd:attribute name="file" type="xsd:string" use="optional"/>
        <xsd:attribute name="probability" type="positiveFloatType"/>
    </xsd:complexType>

    <xsd:complexType name="instantInductionLoopType">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="lane" type="xsd:string" use="required"/>
        <xsd:attribute name="pos" type="xsd:float" use="required"/>
        <xsd:attribute name="file" type="xsd:string" use="required"/>
        <xsd:attribute name="friendlyPos" type="boolType" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="busStopType">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="lane" type="xsd:string" use="required"/>
        <xsd:attribute name="startPos" type="xsd:float"/>
        <xsd:attribute name="endPos" type="xsd:float"/>
        <xsd:attribute name="friendlyPos" type="boolType" use="optional"/>
        <xsd:attribute name="lines" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="calibratorType">
        <xsd:choice maxOccurs="unbounded">
            <xsd:element name="route" type="routeType" minOccurs="0"/>
            <xsd:element name="flow" type="flowCalibratorType" minOccurs="0"/>
        </xsd:choice>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="lane" type="xsd:string" use="required"/>
        <xsd:attribute name="pos" type="xsd:float" use="required"/>
        <xsd:attribute name="friendlyPos" type="boolType" use="optional"/>
        <xsd:attribute name="freq" type="positiveFloatType" use="optional"/>
        <xsd:attribute name="file" type="xsd:string" use="optional"/>
        <xsd:attribute name="output" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="vaporizerType">
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="begin" type="nonNegativeFloatType" use="optional"/>
        <xsd:attribute name="end" type="nonNegativeFloatType" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="polygonType">
        <xsd:sequence>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="color" type="colorType" use="required"/>
        <xsd:attribute name="fill" type="boolType" use="optional"/>
        <xsd:attribute name="layer" type="xsd:float" use="optional"/>
        <xsd:attribute name="shape" type="shapeType" use="required"/>
        <xsd:attribute name="angle" type="xsd:float" use="optional"/>
        <xsd:attribute name="imgFile" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="poiType">
        <xsd:sequence>
            <xsd:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" use="required"/>
        <xsd:attribute name="type" type="xsd:string" use="optional"/>
        <xsd:attribute name="color" type="colorType" use="required"/>
        <xsd:attribute name="layer" type="xsd:float" use="optional"/>
        <xsd:attribute name="x" type="xsd:float" use="optional"/>
        <xsd:attribute name="y" type="xsd:float" use="optional"/>
        <xsd:attribute name="lon" type="xsd:float" use="optional"/>
        <xsd:attribute name="lat" type="xsd:float" use="optional"/>
        <xsd:attribute name="lane" type="xsd:string" use="optional"/>
        <xsd:attribute name="pos" type="xsd:float" use="optional"/>
        <xsd:attribute name="angle" type="xsd:float" use="optional"/>
        <xsd:attribute name="imgFile" type="xsd:string" use="optional"/>
        <xsd:attribute name="width" type="xsd:float" use="optional"/>
        <xsd:attribute name="height" type="xsd:float" use="optional"/>
    </xsd:complexType>

</xsd:schema>

=== eclipse-sumo/sumo/tests/netedit/elements/shapes/poilane/inspect_selected/input_additionalsA.add.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 31.08.2018 10:20:17 by Eclipse SUMO netedit Version b980bbd93f
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/netconvertConfiguration.xsd">

    <input>
        <sumo-net-file value="C:/Users/SUMO-Test/.texttest/tmp/netedit.gui.31Aug101929.812/netedit.gui/shapeElements/poilane/inspect/inspect_id\input_input_netA.net.xml"/>
    </input>

    <output>
        <output-file value="C:/Users/SUMO-Test/.texttest/tmp/netedit.gui.31Aug101929.812/netedit.gui/shapeElements/poilane/inspect/inspect_id\input_netA.net.xml"/>
    </output>

    <processing>
        <offset.disable-normalization value="true"/>
        <lefthand value="false"/>
    </processing>

    <junctions>
        <no-turnarounds value="true"/>
        <junctions.corner-detail value="5"/>
        <junctions.limit-turn-speed value="-1"/>
        <rectangular-lane-cut value="false"/>
    </junctions>

    <pedestrian>
        <walkingareas value="false"/>
    </pedestrian>

    <netedit>
        <additionals-output value="C:/Users/SUMO-Test/.texttest/tmp/netedit.gui.31Aug101929.812/netedit.gui/shapeElements/poilane/inspect/inspect_id\additionals.xml"/>
        <shapes-output value="C:/Users/SUMO-Test/.texttest/tmp/netedit.gui.31Aug101929.812/netedit.gui/shapeElements/poilane/inspect/inspect_id\shapes.xml"/>
    </netedit>

    <visualisation>
        <gui-settings-file value="C:/Users/SUMO-Test/.texttest/tmp/netedit.gui.31Aug101929.812/netedit.gui/shapeElements/poilane/inspect/inspect_id\gui-settings.xml"/>
        <window-size value="700,500"/>
        <window-pos value="50,50"/>
        <gui-testing value="true"/>
        <gui-testing-debug value="true"/>
        <gui-testing-debug-gl value="true"/>
    </visualisation>

    <report>
        <no-warnings value="true"/>
        <error-log value="C:/Users/SUMO-Test/.texttest/tmp/netedit.gui.31Aug101929.812/netedit.gui/shapeElements/poilane/inspect/inspect_id\log.txt"/>
    </report>

</configuration>
-->

<additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">
    <poi id="POI_1" lane="Edge0_1" color="red" layer="202.00" pos="21.36" width="20" height="15" angle="18" friendlyPos="1" imgFile="fileA" name="nameA" posLat="0.1" type="typeA">
        <param key="KeyA1" value="valueA1"/>
        <param key="KeyA3" value="valueA2"/>
        <param key="KeyA2" value="valueA3"/>
    </poi>
    <poi id="POI_2" lane="Edge3_1" color="blue" layer="16.00" pos="26.00" width="19" height="32" angle="21" friendlyPos="false" imgFile="fileB" name="nameB" posLat="4" type="typeA">
        <param key="KeyB1" value="valueB1"/>
        <param key="KeyB3" value="valueB2"/>
        <param key="KeyB2" value="valueB3"/>
    </poi>
</additional>

=== eclipse-sumo/sumo/sumo/tests/sumo/extended/calibrator/high_flow/input_additional.add.xml
<additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo-sim.org/xsd/additional_file.xsd">
    <vType id="t0" speedDev="0.1" speedFactor="1.2" sigma="0"/>
    <calibrator id="calibtest" lane="beg_0" pos="0" output="detector.xml">
        <route id="c1" edges="beg middle end rend"/>
        <!-- 2500 vehs in 3600s -->
        <flow begin="0"    end="1800" route="c1" vehsPerHour="2500" speed="27.8" type="t0" departPos="free" departSpeed="max"/>
        <flow begin="1800" end="3600" route="c1" vehsPerHour="2500" speed="15.0" type="t0" departPos="free" departSpeed="max"/>
        <flow begin="3600" end="5400" route="c1" vehsPerHour="2500" speed="10.0" type="t0" departPos="free" departSpeed="max"/>
        <flow begin="5400" end="7200" route="c1" vehsPerHour="2500" speed="5.0"  type="t0" departPos="free" departSpeed="max"/>
    </calibrator>

    <edgeData id="expect_1250_vehs_0"      begin="0"    end="1800"  file="aggregated_25.xml"/>
    <edgeData id="expect_1250_vehs_3600"   begin="1800" end="3600"  file="aggregated_25.xml"/>
    <edgeData id="expect_1250_vehs_7200"   begin="3600" end="5400"  file="aggregated_25.xml"/>
    <edgeData id="expect_1250_vehs_10800"  begin="5400" end="7200"  file="aggregated_25.xml"/>
</additional>

=== eclipse-sumo/sumo/tests/tools/district/stationDistricts/input_additional.add.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- generated on 2023-03-09 10:41:39 by Eclipse SUMO netedit Version v1_16_0+1097-3a874ee0d52
-->

<additional xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://sumo.dlr.de/xsd/additional_file.xsd">
    <!-- StoppingPlaces -->
    <busStop id="-2609440759" name="Wildau" lane="-255228346#1_0" startPos="0.00" endPos="167.30" friendlyPos="true"/>
    <busStop id="-293605245" name="Königs Wusterhausen" lane="-33142145#0_0" startPos="0.00" endPos="200.00" friendlyPos="true"/>
    <busStop id="-42118188" name="Niederlehme" lane="-176623658#0_0" startPos="2283.82" endPos="2483.82" friendlyPos="true"/>
    <busStop id="-42132938" name="Königs Wusterhausen" lane="-334912225#0_0" startPos="8.44" endPos="208.44" friendlyPos="true"/>
    <busStop id="-428356215" name="Wildau" lane="-255228348#1_0" startPos="0.00" endPos="167.78" friendlyPos="true"/>
    <busStop id="-428759039" name="Königs Wusterhausen" lane="-294730183_0" startPos="0.00" endPos="200.00" friendlyPos="true"/>
    <busStop id="-59143907" name="Zeuthen" lane="-441932166#4_0" startPos="0.00" endPos="132.64" friendlyPos="true"/>
    <busStop id="102020660" name="Bestensee" lane="8044251#0_0" startPos="0.00" endPos="135.62" friendlyPos="true" lines="RB24 RE7"/>
    <busStop id="102026599" name="Zeesen" lane="337460727#2_0" startPos="1482.15" endPos="1682.15" friendlyPos="true" lines="RB24 RE7"/>
    <busStop id="1095078266" name="Eichwalde" lane="27006469#3_0" startPos="0.00" endPos="195.91" friendlyPos="true" lines="S8 S46"/>
    <busStop id="247120025" name="Eichwalde" lane="22955557#6_0" startPos="28.81" endPos="228.81" friendlyPos="true" lines="S8 S46"/>
    <busStop id="2609440759" name="Wildau" lane="255228346#1_0" startPos="0.00" endPos="167.30" friendlyPos="true" lines="S46"/>
    <busStop id="293605245" name="Königs Wusterhausen" lane="33141915#1_0" startPos="460.30" endPos="660.30" friendlyPos="true" lines="RB36 RB22"/>
    <busStop id="295049552" name="Zeesen" lane="8044251#2_0" startPos="2009.86" endPos="2209.86" friendlyPos="true" lines="RB24 RE7"/>
    <busStop id="296020395" name="Zeuthen" lane="42220072#1_0" startPos="0.00" endPos="170.92" friendlyPos="true" lines="S8 S46"/>
    <busStop id="42118188" name="Niederlehme" lane="-8044249_0" startPos="626.25" endPos="826.25" friendlyPos="true" lines="RB36"/>
    <busStop id="42132938" name="Königs Wusterhausen" lane="742458418#1_0" startPos="140.63" endPos="340.63" friendlyPos="true" lines="RB24 RB22 RE2 RE7"/>
    <busStop id="428356215" name="Wildau" lane="255228348#1_0" startPos="0.00" endPos="167.78" friendlyPos="true" lines="S46"/>
    <busStop id="428759039" name="Königs Wusterhausen" lane="742458420_0" startPos="11.78" endPos="211.78" friendlyPos="true" lines="S46"/>
    <busStop id="59143907" name="Zeuthen" lane="441932166#4_0" startPos="0.00" endPos="132.64" friendlyPos="true" lines="S8 S46"/>
</additional>
